package http_executor

import (
	"fmt"
	"regexp"
	"runtime/debug"
	"strconv"
	"strings"
)

const modulePath = "github.com/1inch/1inch-sdk-go/v4"

// unknownVersion is reported when the build carries no usable version: it is
// valid semver (so the header always parses), sorts below every real release,
// and its build metadata states why no release number is available
const unknownVersion = "v0.0.0+unknown"

// semverRegex is the official semver.org grammar with the leading "v" Go module
// versions carry
var semverRegex = regexp.MustCompile(`^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`)

// Pseudo-version forms generated by the Go toolchain for untagged commits:
// vX.Y.(Z+1)-0.yyyymmddhhmmss-abcdef123456 descends from release tag vX.Y.Z, and
// vX.Y.Z-pre.0.yyyymmddhhmmss-abcdef123456 descends from prerelease tag vX.Y.Z-pre
var (
	pseudoAfterReleaseRegex    = regexp.MustCompile(`^v(\d+)\.(\d+)\.(\d+)-0\.(\d{14})-([0-9a-f]{12})$`)
	pseudoAfterPrereleaseRegex = regexp.MustCompile(`^(v\d+\.\d+\.\d+-.+?)\.0\.(\d{14})-([0-9a-f]{12})$`)
)

var userAgent = buildUserAgent()

func buildUserAgent() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		info = nil
	}
	return "1inch-dev-portal-client-go:" + sdkVersionFromBuildInfo(info)
}

// sdkVersionFromBuildInfo resolves the SDK version the running binary was built
// against. The result is always valid semver: release and prerelease tags are
// reported verbatim, pseudo-versions are rewritten to their base tag with the
// commit details preserved as build metadata (so the version part always names a
// published release), and builds with no usable version report a semver-valid
// sentinel. No version information is dropped.
func sdkVersionFromBuildInfo(info *debug.BuildInfo) string {
	if info == nil {
		return unknownVersion
	}

	for _, dep := range info.Deps {
		if dep.Path != modulePath {
			continue
		}
		// A replace directive swaps in different code, so the replacement's
		// version describes what actually runs, whatever module path it has
		effective := dep
		if dep.Replace != nil {
			effective = dep.Replace
		}
		return normalizeVersion(effective.Version)
	}

	// When built from within this repository the module is Main, not a dependency
	if strings.HasPrefix(info.Main.Path, modulePath) {
		return normalizeVersion(info.Main.Version)
	}

	return unknownVersion
}

// normalizeVersion maps a module version to the semver value reported in the
// User-Agent header
func normalizeVersion(version string) string {
	if base, ok := pseudoVersionBase(version); ok {
		return base
	}
	if semverRegex.MatchString(version) {
		return version
	}
	return unknownVersion
}

// pseudoVersionBase rewrites a pseudo-version to the tag it descends from, with
// the commit timestamp and hash preserved as semver build metadata:
// v4.1.1-0.20260801120000-abcdef123456 becomes v4.1.0+dev.20260801120000.abcdef123456
func pseudoVersionBase(version string) (string, bool) {
	if m := pseudoAfterReleaseRegex.FindStringSubmatch(version); m != nil {
		patch, err := strconv.Atoi(m[3])
		if err != nil || patch < 1 {
			return "", false
		}
		return fmt.Sprintf("v%s.%s.%d+dev.%s.%s", m[1], m[2], patch-1, m[4], m[5]), true
	}
	if m := pseudoAfterPrereleaseRegex.FindStringSubmatch(version); m != nil && semverRegex.MatchString(m[1]) {
		return fmt.Sprintf("%s+dev.%s.%s", m[1], m[2], m[3]), true
	}
	return "", false
}
