// Package balance provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package balance

// BalancesAndAllowancesResponse defines model for BalancesAndAllowancesResponse.
type BalancesAndAllowancesResponse struct {
	Address  string                 `json:"address"`
	Decimals float32                `json:"decimals"`
	IsCustom bool                   `json:"isCustom"`
	LogoURI  string                 `json:"logoURI"`
	Name     string                 `json:"name"`
	Symbol   string                 `json:"symbol"`
	Tags     []string               `json:"tags"`
	Tracked  *bool                  `json:"tracked,omitempty"`
	Type     string                 `json:"type"`
	Wallets  map[string]interface{} `json:"wallets"`
}

// CustomTokensAndWalletsRequest defines model for CustomTokensAndWalletsRequest.
type CustomTokensAndWalletsRequest struct {
	// Tokens List of custom tokens
	Tokens []string `json:"tokens"`

	// Wallets List of wallets
	Wallets []string `json:"wallets"`
}

// CustomTokensRequest defines model for CustomTokensRequest.
type CustomTokensRequest struct {
	// Tokens List of custom tokens
	Tokens []string `json:"tokens"`
}

// GetAggregatedBalancesAndAllowancesParams defines parameters for GetBalancesAndAllowances.
type GetAggregatedBalancesAndAllowancesParams struct {
	Wallets     []string `url:"wallets" json:"wallets"`
	FilterEmpty bool     `url:"filterEmpty" json:"filterEmpty"`
}

// ChainV12ControllerGetCustomAllowancesJSONRequestBody defines body for ChainV12ControllerGetCustomAllowances for application/json ContentType.
type ChainV12ControllerGetCustomAllowancesJSONRequestBody = CustomTokensRequest

// ChainV12ControllerGetCustomAllowancesAndBalancesJSONRequestBody defines body for ChainV12ControllerGetCustomAllowancesAndBalances for application/json ContentType.
type ChainV12ControllerGetCustomAllowancesAndBalancesJSONRequestBody = CustomTokensRequest

// ChainV12ControllerGetBalancesByMultipleWalletsJSONRequestBody defines body for ChainV12ControllerGetBalancesByMultipleWallets for application/json ContentType.
type ChainV12ControllerGetBalancesByMultipleWalletsJSONRequestBody = CustomTokensAndWalletsRequest

// ChainV12ControllerGetCustomBalancesJSONRequestBody defines body for ChainV12ControllerGetCustomBalances for application/json ContentType.
type ChainV12ControllerGetCustomBalancesJSONRequestBody = CustomTokensRequest
