// Package txbroadcast provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package txbroadcast

// BroadcastRequest defines model for BroadcastRequest.
type BroadcastRequest struct {
	// RawTransaction The raw transaction data
	//
	// Example: 0xf86...
	RawTransaction string `json:"rawTransaction"`
}

// BroadcastResponse defines model for BroadcastResponse.
type BroadcastResponse struct {
	// TransactionHash The transaction hash
	//
	// Example: 0x123...
	TransactionHash string `json:"transactionHash"`
}

// BroadcastPublicTransactionJSONRequestBody defines body for BroadcastPublicTransaction for application/json ContentType.
type BroadcastPublicTransactionJSONRequestBody = BroadcastRequest

// BroadcastPrivateTransactionJSONRequestBody defines body for BroadcastPrivateTransaction for application/json ContentType.
type BroadcastPrivateTransactionJSONRequestBody = BroadcastRequest
