// Package fusionplus provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package fusionplus

// Defines values for GetQuoteOutputRecommendedPreset.
const (
	Custom GetQuoteOutputRecommendedPreset = "custom"
	Fast   GetQuoteOutputRecommendedPreset = "fast"
	Medium GetQuoteOutputRecommendedPreset = "medium"
	Slow   GetQuoteOutputRecommendedPreset = "slow"
)

// AuctionPoint defines model for AuctionPoint.
type AuctionPoint struct {
	Coefficient float32 `json:"coefficient"`
	Delay       float32 `json:"delay"`
}

// BuildOrderBody defines model for BuildOrderBody.
type BuildOrderBody struct {
	Quote GetQuoteOutput `json:"quote"`

	// SecretsHashList keccak256(secret)[]
	SecretsHashList string `json:"secretsHashList"`
}

// BuildOrderOutput defines model for BuildOrderOutput.
type BuildOrderOutput struct {
	// Extension CrossChain order extension
	Extension string `json:"extension"`

	// OrderHash Hash of CrossChain order
	OrderHash string `json:"orderHash"`

	// TypedData EIP712 Typed Data
	TypedData map[string]interface{} `json:"typedData"`
}

// CustomPresetParams defines model for CustomPresetParams.
type CustomPresetParams = map[string]interface{}

// GasCostConfig defines model for GasCostConfig.
type GasCostConfig struct {
	GasBumpEstimate  float32 `json:"gasBumpEstimate"`
	GasPriceEstimate string  `json:"gasPriceEstimate"`
}

// GetQuoteOutput defines model for GetQuoteOutput.
type GetQuoteOutput struct {
	// DstEscrowFactory Escrow factory contract address at destination chain
	DstEscrowFactory string       `json:"dstEscrowFactory"`
	DstSafetyDeposit string       `json:"dstSafetyDeposit"`
	DstTokenAmount   string       `json:"dstTokenAmount"`
	Presets          QuotePresets `json:"presets"`
	Prices           PairCurrency `json:"prices"`

	// QuoteId Current generated quote id, should be passed with order
	QuoteId map[string]interface{} `json:"quoteId"`

	// RecommendedPreset suggested preset
	RecommendedPreset GetQuoteOutputRecommendedPreset `json:"recommendedPreset"`

	// SrcEscrowFactory Escrow factory contract address at source chain
	SrcEscrowFactory string       `json:"srcEscrowFactory"`
	SrcSafetyDeposit string       `json:"srcSafetyDeposit"`
	SrcTokenAmount   string       `json:"srcTokenAmount"`
	TimeLocks        TimeLocks    `json:"timeLocks"`
	Volume           PairCurrency `json:"volume"`

	// Whitelist current executors whitelist addresses
	Whitelist []string `json:"whitelist"`
}

// GetQuoteOutputRecommendedPreset suggested preset
type GetQuoteOutputRecommendedPreset string

// PairCurrency defines model for PairCurrency.
type PairCurrency struct {
	Usd TokenPair `json:"usd"`
}

// Preset defines model for Preset.
type Preset struct {
	AllowMultipleFills bool                   `json:"allowMultipleFills"`
	AllowPartialFills  bool                   `json:"allowPartialFills"`
	AuctionDuration    float32                `json:"auctionDuration"`
	AuctionEndAmount   string                 `json:"auctionEndAmount"`
	AuctionStartAmount string                 `json:"auctionStartAmount"`
	CostInDstToken     string                 `json:"costInDstToken"`
	ExclusiveResolver  map[string]interface{} `json:"exclusiveResolver"`
	GasCost            GasCostConfig          `json:"gasCost"`
	InitialRateBump    float32                `json:"initialRateBump"`
	Points             []AuctionPoint         `json:"points"`
	SecretsCount       float32                `json:"secretsCount"`

	// StartAmount auction start amount taking into account gas bump
	StartAmount    string  `json:"startAmount"`
	StartAuctionIn float32 `json:"startAuctionIn"`
}

// QuotePresets defines model for QuotePresets.
type QuotePresets struct {
	Custom *Preset `json:"custom,omitempty"`
	Fast   Preset  `json:"fast"`
	Medium Preset  `json:"medium"`
	Slow   Preset  `json:"slow"`
}

// TimeLocks defines model for TimeLocks.
type TimeLocks struct {
	DstCancellation       float32 `json:"dstCancellation"`
	DstPublicWithdrawal   float32 `json:"dstPublicWithdrawal"`
	DstWithdrawal         float32 `json:"dstWithdrawal"`
	SrcCancellation       float32 `json:"srcCancellation"`
	SrcPublicCancellation float32 `json:"srcPublicCancellation"`
	SrcPublicWithdrawal   float32 `json:"srcPublicWithdrawal"`
	SrcWithdrawal         float32 `json:"srcWithdrawal"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	DstToken string `json:"dstToken"`
	SrcToken string `json:"srcToken"`
}

// QuoterControllerBuildQuoteTypedDataParams defines parameters for QuoterControllerBuildQuoteTypedData.
type QuoterControllerBuildQuoteTypedDataParams struct {
	// SrcChain Id of source chain
	SrcChain float32 `url:"srcChain" json:"srcChain"`

	// DstChain Id of destination chain
	DstChain float32 `url:"dstChain" json:"dstChain"`

	// SrcTokenAddress Address of "SOURCE" token
	SrcTokenAddress string `url:"srcTokenAddress" json:"srcTokenAddress"`

	// DstTokenAddress Address of "DESTINATION" token
	DstTokenAddress string `url:"dstTokenAddress" json:"dstTokenAddress"`

	// Amount Amount to take from "SOURCE" token to get "DESTINATION" token
	Amount float32 `url:"amount" json:"amount"`

	// WalletAddress An address of the wallet or contract who will create Fusion order
	WalletAddress string `url:"walletAddress" json:"walletAddress"`

	// Fee fee in bps format, 1% is equal to 100bps
	Fee float32 `url:"fee,omitempty" json:"fee,omitempty"`

	// Source Frontend or some other source selector
	Source string `url:"source,omitempty" json:"source,omitempty"`

	// IsPermit2 permit2 allowance transfer encoded call
	IsPermit2 string `url:"isPermit2,omitempty" json:"isPermit2,omitempty"`

	// IsMobile Enabled flag allows to save quote for Mobile History
	IsMobile string `url:"isMobile,omitempty" json:"isMobile,omitempty"`

	// FeeReceiver In case fee non zero -> the fee will be transferred to this address
	FeeReceiver string `url:"feeReceiver,omitempty" json:"feeReceiver,omitempty"`

	// Permit permit, user approval sign
	Permit string `url:"permit,omitempty" json:"permit,omitempty"`

	// Preset fast/medium/slow/custom
	Preset string `url:"preset,omitempty" json:"preset,omitempty"`
}

// QuoterControllerGetQuoteParams defines parameters for QuoterControllerGetQuote.
type QuoterControllerGetQuoteParams struct {
	// SrcChain Id of source chain
	SrcChain float32 `url:"srcChain" json:"srcChain"`

	// DstChain Id of destination chain
	DstChain float32 `url:"dstChain" json:"dstChain"`

	// SrcTokenAddress Address of "SOURCE" token in source chain
	SrcTokenAddress string `url:"srcTokenAddress" json:"srcTokenAddress"`

	// DstTokenAddress Address of "DESTINATION" token in destination chain
	DstTokenAddress string `url:"dstTokenAddress" json:"dstTokenAddress"`

	// Amount Amount to take from "SOURCE" token to get "DESTINATION" token
	Amount float32 `url:"amount" json:"amount"`

	// WalletAddress An address of the wallet or contract in source chain who will create Fusion order
	WalletAddress string `url:"walletAddress" json:"walletAddress"`

	// EnableEstimate if enabled then get estimation from 1inch swap builder and generates quoteId, by default is false
	EnableEstimate bool `url:"enableEstimate" json:"enableEstimate"`

	// Fee fee in bps format, 1% is equal to 100bps
	Fee float32 `url:"fee,omitempty" json:"fee,omitempty"`

	// IsPermit2 permit2 allowance transfer encoded call
	IsPermit2 string `url:"isPermit2,omitempty" json:"isPermit2,omitempty"`

	// Permit permit, user approval sign
	Permit string `url:"permit,omitempty" json:"permit,omitempty"`
}

// QuoterControllerGetQuoteWithCustomPresetsParams defines parameters for QuoterControllerGetQuoteWithCustomPresets.
type QuoterControllerGetQuoteWithCustomPresetsParams struct {
	// SrcChain Id of source chain
	SrcChain float32 `url:"srcChain" json:"srcChain"`

	// DstChain Id of destination chain
	DstChain float32 `url:"dstChain" json:"dstChain"`

	// SrcTokenAddress Address of "SOURCE" token
	SrcTokenAddress string `url:"srcTokenAddress" json:"srcTokenAddress"`

	// DstTokenAddress Address of "DESTINATION" token
	DstTokenAddress string `url:"dstTokenAddress" json:"dstTokenAddress"`

	// Amount Amount to take from "SOURCE" token to get "DESTINATION" token
	Amount float32 `url:"amount" json:"amount"`

	// WalletAddress An address of the wallet or contract who will create Fusion order
	WalletAddress string `url:"walletAddress" json:"walletAddress"`

	// EnableEstimate if enabled then get estimation from 1inch swap builder and generates quoteId, by default is false
	EnableEstimate bool `url:"enableEstimate" json:"enableEstimate"`

	// Fee fee in bps format, 1% is equal to 100bps
	Fee float32 `url:"fee,omitempty" json:"fee,omitempty"`

	// IsPermit2 permit2 allowance transfer encoded call
	IsPermit2 string `url:"isPermit2,omitempty" json:"isPermit2,omitempty"`

	// Permit permit, user approval sign
	Permit string `url:"permit,omitempty" json:"permit,omitempty"`
}

// QuoterControllerBuildQuoteTypedDataJSONRequestBody defines body for QuoterControllerBuildQuoteTypedData for application/json ContentType.
type QuoterControllerBuildQuoteTypedDataJSONRequestBody = BuildOrderBody

// QuoterControllerGetQuoteWithCustomPresetsJSONRequestBody defines body for QuoterControllerGetQuoteWithCustomPresets for application/json ContentType.
type QuoterControllerGetQuoteWithCustomPresetsJSONRequestBody = CustomPresetParams
