// Package fusionplus provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fusionplus

// Defines values for EscrowEventDataOutputAction.
const (
	DstEscrowCreated EscrowEventDataOutputAction = "dst_escrow_created"
	EscrowCancelled  EscrowEventDataOutputAction = "escrow_cancelled"
	FundsRescued     EscrowEventDataOutputAction = "funds_rescued"
	SrcEscrowCreated EscrowEventDataOutputAction = "src_escrow_created"
	Withdrawn        EscrowEventDataOutputAction = "withdrawn"
)

// Valid indicates whether the value is a known member of the EscrowEventDataOutputAction enum.
func (e EscrowEventDataOutputAction) Valid() bool {
	switch e {
	case DstEscrowCreated:
		return true
	case EscrowCancelled:
		return true
	case FundsRescued:
		return true
	case SrcEscrowCreated:
		return true
	case Withdrawn:
		return true
	default:
		return false
	}
}

// Defines values for EscrowEventDataOutputSide.
const (
	Dst EscrowEventDataOutputSide = "dst"
	Src EscrowEventDataOutputSide = "src"
)

// Valid indicates whether the value is a known member of the EscrowEventDataOutputSide enum.
func (e EscrowEventDataOutputSide) Valid() bool {
	switch e {
	case Dst:
		return true
	case Src:
		return true
	default:
		return false
	}
}

// Defines values for FillOutputDtoStatus.
const (
	FillOutputDtoStatusExecuted  FillOutputDtoStatus = "executed"
	FillOutputDtoStatusPending   FillOutputDtoStatus = "pending"
	FillOutputDtoStatusRefunded  FillOutputDtoStatus = "refunded"
	FillOutputDtoStatusRefunding FillOutputDtoStatus = "refunding"
)

// Valid indicates whether the value is a known member of the FillOutputDtoStatus enum.
func (e FillOutputDtoStatus) Valid() bool {
	switch e {
	case FillOutputDtoStatusExecuted:
		return true
	case FillOutputDtoStatusPending:
		return true
	case FillOutputDtoStatusRefunded:
		return true
	case FillOutputDtoStatusRefunding:
		return true
	default:
		return false
	}
}

// Defines values for GetOrderFillsByHashOutputStatus.
const (
	GetOrderFillsByHashOutputStatusCancelled GetOrderFillsByHashOutputStatus = "cancelled"
	GetOrderFillsByHashOutputStatusExecuted  GetOrderFillsByHashOutputStatus = "executed"
	GetOrderFillsByHashOutputStatusExpired   GetOrderFillsByHashOutputStatus = "expired"
	GetOrderFillsByHashOutputStatusPending   GetOrderFillsByHashOutputStatus = "pending"
	GetOrderFillsByHashOutputStatusRefunded  GetOrderFillsByHashOutputStatus = "refunded"
	GetOrderFillsByHashOutputStatusRefunding GetOrderFillsByHashOutputStatus = "refunding"
)

// Valid indicates whether the value is a known member of the GetOrderFillsByHashOutputStatus enum.
func (e GetOrderFillsByHashOutputStatus) Valid() bool {
	switch e {
	case GetOrderFillsByHashOutputStatusCancelled:
		return true
	case GetOrderFillsByHashOutputStatusExecuted:
		return true
	case GetOrderFillsByHashOutputStatusExpired:
		return true
	case GetOrderFillsByHashOutputStatusPending:
		return true
	case GetOrderFillsByHashOutputStatusRefunded:
		return true
	case GetOrderFillsByHashOutputStatusRefunding:
		return true
	default:
		return false
	}
}

// Defines values for GetOrderFillsByHashOutputValidation.
const (
	FailedToDecodeRemaining            GetOrderFillsByHashOutputValidation = "failed-to-decode-remaining"
	FailedToParsePermitDetails         GetOrderFillsByHashOutputValidation = "failed-to-parse-permit-details"
	InvalidPermitSignature             GetOrderFillsByHashOutputValidation = "invalid-permit-signature"
	InvalidPermitSigner                GetOrderFillsByHashOutputValidation = "invalid-permit-signer"
	InvalidPermitSpender               GetOrderFillsByHashOutputValidation = "invalid-permit-spender"
	InvalidSignature                   GetOrderFillsByHashOutputValidation = "invalid-signature"
	NotEnoughAllowance                 GetOrderFillsByHashOutputValidation = "not-enough-allowance"
	NotEnoughBalance                   GetOrderFillsByHashOutputValidation = "not-enough-balance"
	OrderPredicateReturnedFalse        GetOrderFillsByHashOutputValidation = "order-predicate-returned-false"
	UnknownFailure                     GetOrderFillsByHashOutputValidation = "unknown-failure"
	UnknownPermitVersion               GetOrderFillsByHashOutputValidation = "unknown-permit-version"
	Valid                              GetOrderFillsByHashOutputValidation = "valid"
	WrongEpochManagerAndBitInvalidator GetOrderFillsByHashOutputValidation = "wrong-epoch-manager-and-bit-invalidator"
)

// Valid indicates whether the value is a known member of the GetOrderFillsByHashOutputValidation enum.
func (e GetOrderFillsByHashOutputValidation) Valid() bool {
	switch e {
	case FailedToDecodeRemaining:
		return true
	case FailedToParsePermitDetails:
		return true
	case InvalidPermitSignature:
		return true
	case InvalidPermitSigner:
		return true
	case InvalidPermitSpender:
		return true
	case InvalidSignature:
		return true
	case NotEnoughAllowance:
		return true
	case NotEnoughBalance:
		return true
	case OrderPredicateReturnedFalse:
		return true
	case UnknownFailure:
		return true
	case UnknownPermitVersion:
		return true
	case Valid:
		return true
	case WrongEpochManagerAndBitInvalidator:
		return true
	default:
		return false
	}
}

// Defines values for ReadyToExecutePublicActionAction.
const (
	Cancel   ReadyToExecutePublicActionAction = "cancel"
	Withdraw ReadyToExecutePublicActionAction = "withdraw"
)

// Valid indicates whether the value is a known member of the ReadyToExecutePublicActionAction enum.
func (e ReadyToExecutePublicActionAction) Valid() bool {
	switch e {
	case Cancel:
		return true
	case Withdraw:
		return true
	default:
		return false
	}
}

// Defines values for ResolverDataOutputOrderType.
const (
	MultipleFills ResolverDataOutputOrderType = "MultipleFills"
	SingleFill    ResolverDataOutputOrderType = "SingleFill"
)

// Valid indicates whether the value is a known member of the ResolverDataOutputOrderType enum.
func (e ResolverDataOutputOrderType) Valid() bool {
	switch e {
	case MultipleFills:
		return true
	case SingleFill:
		return true
	default:
		return false
	}
}

// ActiveOrdersOutput defines model for ActiveOrdersOutput.
type ActiveOrdersOutput struct {
	// AuctionEndDate End date of the auction for this order.
	//
	// Example: 1634025600000
	AuctionEndDate float32 `json:"auctionEndDate"`

	// AuctionStartDate Start date of the auction for this order.
	//
	// Example: 1634025600000
	AuctionStartDate float32 `json:"auctionStartDate"`

	// Deadline Deadline by which the order must be filled.
	//
	// Example: 1634025600000
	Deadline float32 `json:"deadline"`

	// DstChainId Identifier of the chain where the taker asset is located.
	//
	// Example: 2
	DstChainId int `json:"dstChainId"`

	// Extension An interaction call data. ABI encoded set of makerAssetSuffix, takerAssetSuffix, makingAmountGetter, takingAmountGetter, predicate, permit, preInteraction, postInteraction.If extension exists then lowest 160 bits of the order salt must be equal to the lowest 160 bits of the extension hash
	//
	// Example: 0x
	Extension string `json:"extension"`

	// Fills Array of fills.
	Fills []string `json:"fills"`

	// IsMakerContract True if order signed by contract (GnosisSafe, etc.)
	//
	// Example: true
	IsMakerContract bool `json:"isMakerContract"`

	// MakerAllowance Amount of the maker asset allowance.
	//
	// Example: 100000000000000000
	MakerAllowance string `json:"makerAllowance"`

	// MakerBalance Amount of the maker asset balance.
	//
	// Example: 100000000000000000
	MakerBalance string             `json:"makerBalance"`
	Order        CrossChainOrderDto `json:"order"`

	// OrderHash Unique identifier of the order.
	//
	// Example: 0x496755a88564d8ded6759dff0252d3e6c3ef1fe42b4fa1bbc3f03bd2674f1078
	OrderHash string `json:"orderHash"`

	// QuoteId Identifier of the quote associated with this order.
	QuoteId string `json:"quoteId"`

	// RemainingMakerAmount Remaining amount of the maker asset that can still be filled.
	//
	// Example: 100000000000000000
	RemainingMakerAmount string `json:"remainingMakerAmount"`

	// SecretHashes Array of secret hashes.
	//
	// Example: ["0x2048b38093dc53876b2bbd230ee8999791153db01de425112f449d018094e116","0x7972c1498893bb9b88baddc9decb78d8defdcc7a182a72edd8724498c75f088d","0x6d5b8f0b1f8a28564ff65e5f9c4d8a8a6babfb318bca6ecc9d872a3abe8a4ea0"]
	SecretHashes [][]interface{} `json:"secretHashes,omitempty"`

	// Signature Signature of the order.
	//
	// Example: 0xf7739f12038fa25a57b51b3fb26fd68bd4b80b534c9ff2a1fd396234b7a8f59308b573db71f7c9598746ecfe6f7f2a962a9d31a1229fc570044ebf0b4bc5db0c
	Signature string `json:"signature"`

	// SrcChainId Identifier of the chain where the maker asset is located.
	//
	// Example: 1
	SrcChainId int `json:"srcChainId"`
}

// AuctionPointOutput defines model for AuctionPointOutput.
type AuctionPointOutput struct {
	// Coefficient The rate bump from the order min taker amount
	//
	// Example: 200
	Coefficient float32 `json:"coefficient"`

	// Delay The delay in seconds from the previous point or auction start time
	//
	// Example: 234
	Delay float32 `json:"delay"`
}

// CrossChainOrderDto defines model for CrossChainOrderDto.
type CrossChainOrderDto struct {
	// Maker Address of the account creating the order (maker) in src chain.
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FA
	Maker string `json:"maker"`

	// MakerAsset Identifier of the asset being offered by the maker in src chain.
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FC
	MakerAsset string `json:"makerAsset"`

	// MakerTraits Includes some flags like, allow multiple fills, is partial fill allowed or not, price improvement, nonce, deadline etc.
	//
	// Example: 0x
	MakerTraits string `json:"makerTraits"`

	// MakingAmount Amount of the makerAsset being offered by the maker in src chain.
	//
	// Example: 100000000000000000
	MakingAmount string `json:"makingAmount"`

	// Receiver Address of the account receiving the assets (receiver), if different from maker in dst chain.
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FB
	Receiver string `json:"receiver"`

	// Salt Some unique value. It is necessary to be able to create cross chain orders with the same parameters (so that they have a different hash), Lowest 160 bits of the order salt must be equal to the lowest 160 bits of the extension hash
	Salt string `json:"salt"`

	// TakerAsset Identifier of the asset being requested by the maker in exchange in dst chain.
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FD
	TakerAsset string `json:"takerAsset"`

	// TakingAmount Amount of the takerAsset being requested by the maker in dst chain.
	//
	// Example: 100000000000000000
	TakingAmount string `json:"takingAmount"`
}

// EscrowEventDataOutput defines model for EscrowEventDataOutput.
type EscrowEventDataOutput struct {
	// Action Action of the escrow event
	//
	// Example: src_escrow_created
	Action EscrowEventDataOutputAction `json:"action"`

	// BlockTimestamp Unix timestamp in milliseconds
	//
	// Example: 123123123123
	BlockTimestamp float32 `json:"blockTimestamp"`

	// Side Side of the escrow event SRC or DST
	//
	// Example: src
	Side EscrowEventDataOutputSide `json:"side"`

	// TransactionHash Transaction hash
	//
	// Example: 0x806039f5149065924ad52de616b50abff488c986716d052e9c160887bc09e559
	TransactionHash string `json:"transactionHash"`
}

// EscrowEventDataOutputAction Action of the escrow event
//
// Example: src_escrow_created
type EscrowEventDataOutputAction string

// EscrowEventDataOutputSide Side of the escrow event SRC or DST
//
// Example: src
type EscrowEventDataOutputSide string

// EscrowFactory defines model for EscrowFactory.
type EscrowFactory struct {
	// Address actual escrow factory contract address
	Address string `json:"address"`
}

// FillOutputDto defines model for FillOutputDto.
type FillOutputDto struct {
	EscrowEvents []EscrowEventDataOutput `json:"escrowEvents"`

	// FilledAuctionTakerAmount Amount of the takerAsset filled in dst chain.
	//
	// Example: 100000000000000000
	FilledAuctionTakerAmount string `json:"filledAuctionTakerAmount"`

	// FilledMakerAmount Amount of the makerAsset filled in src chain.
	//
	// Example: 100000000000000000
	FilledMakerAmount string `json:"filledMakerAmount"`

	// Status Fill status
	//
	// Example: pending
	Status FillOutputDtoStatus `json:"status"`

	// TxHash Transaction hash
	//
	// Example: 0x806039f5149065924ad52de616b50abff488c986716d052e9c160887bc09e559
	TxHash string `json:"txHash"`
}

// FillOutputDtoStatus Fill status
//
// Example: pending
type FillOutputDtoStatus string

// GetActiveOrdersOutput defines model for GetActiveOrdersOutput.
type GetActiveOrdersOutput struct {
	Items []ActiveOrdersOutput `json:"items"`
	Meta  Meta                 `json:"meta"`
}

// GetOrderByMakerOutput defines model for GetOrderByMakerOutput.
type GetOrderByMakerOutput struct {
	Items []ActiveOrdersOutput `json:"items"`
	Meta  Meta                 `json:"meta"`
}

// GetOrderFillsByHashOutput defines model for GetOrderFillsByHashOutput.
type GetOrderFillsByHashOutput struct {
	// ApproximateTakingAmount Approximate amount of the takerAsset being requested by the maker in dst chain.
	//
	// Example: 100000000000000000
	ApproximateTakingAmount string `json:"approximateTakingAmount"`

	// AuctionDuration Unix timestamp in milliseconds
	//
	// Example: 123123123123
	AuctionDuration float32 `json:"auctionDuration"`

	// AuctionStartDate Unix timestamp in milliseconds
	//
	// Example: 123123123123
	AuctionStartDate float32 `json:"auctionStartDate"`

	// CancelTx Example: 0xa2768a9826b2c45a6937010ce21a91b1da9f8c7aa5194f68aa99306b22518b41
	CancelTx map[string]interface{} `json:"cancelTx"`

	// Cancelable Is order cancelable
	//
	// Example: true
	Cancelable bool `json:"cancelable"`

	// CreatedAt Unix timestamp in milliseconds
	//
	// Example: 123123123123
	CreatedAt float32 `json:"createdAt"`

	// DstChainId Identifier of the chain where the taker asset is located.
	//
	// Example: 2
	DstChainId       int    `json:"dstChainId"`
	DstTokenPriceUsd string `json:"dstTokenPriceUsd"`

	// Extension An interaction call data. ABI encoded set of makerAssetSuffix, takerAssetSuffix, makingAmountGetter, takingAmountGetter, predicate, permit, preInteraction, postInteraction.If extension exists then lowest 160 bits of the order salt must be equal to the lowest 160 bits of the extension hash
	Extension string `json:"extension"`

	// Fills Fills
	Fills []FillOutputDto `json:"fills"`

	// InitialRateBump Initial rate bump
	//
	// Example: 1000
	InitialRateBump float32                  `json:"initialRateBump"`
	Order           LimitOrderV4StructOutput `json:"order"`

	// OrderHash Order hash
	//
	// Example: 0x496755a88564d8ded6759dff0252d3e6c3ef1fe42b4fa1bbc3f03bd2674f1078
	OrderHash string               `json:"orderHash"`
	Points    []AuctionPointOutput `json:"points"`

	// SrcChainId Identifier of the chain where the maker asset is located.
	//
	// Example: 1
	SrcChainId       int    `json:"srcChainId"`
	SrcTokenPriceUsd string `json:"srcTokenPriceUsd"`

	// Status Order status
	//
	// Example: pending
	Status GetOrderFillsByHashOutputStatus `json:"status"`

	// TakerAsset Identifier of the asset being requested by the maker in exchange in dst chain.
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FD
	TakerAsset string `json:"takerAsset"`

	// TimeLocks TimeLocks without deployedAt
	//
	// Example: 0xfc000000840000000c000001bc00000144000000a800000024
	TimeLocks string `json:"timeLocks"`

	// Validation Order validation status
	//
	// Example: valid
	Validation GetOrderFillsByHashOutputValidation `json:"validation"`
}

// GetOrderFillsByHashOutputStatus Order status
//
// Example: pending
type GetOrderFillsByHashOutputStatus string

// GetOrderFillsByHashOutputValidation Order validation status
//
// Example: valid
type GetOrderFillsByHashOutputValidation string

// Immutables defines model for Immutables.
type Immutables struct {
	// Amount Amount of token to receive
	//
	// Example: 1000000000000000000
	Amount string `json:"amount"`

	// Hashlock keccak256(secret(idx))
	//
	// Example: 0x03f9ebf9075dfaae76c43b7443d07399609ffe24a5d435045fe4d3bf82d9fce4
	Hashlock string `json:"hashlock"`

	// Maker Maker's address which will receive tokens
	//
	// Example: 0xe75eD6F453c602Bd696cE27AF11565eDc9b46B0D
	Maker string `json:"maker"`

	// OrderHash Order's hash 32 bytes hex sting
	//
	// Example: 0x496755a88564d8ded6759dff0252d3e6c3ef1fe42b4fa1bbc3f03bd2674f1078
	OrderHash string `json:"orderHash"`

	// SafetyDeposit Security deposit in chain's native currency
	//
	// Example: 50000000000000000000
	SafetyDeposit string `json:"safetyDeposit"`

	// Taker Escrow creation initiator address
	//
	// Example: 0x00000000009E50a7dDb7a7B0e2ee6604fd120E49
	Taker string `json:"taker"`

	// Timelocks Encoded timelocks. To decode use: https://github.com/1inch/cross-chain-sdk/blob/master/src/cross-chain-order/time-locks/time-locks.ts
	//
	// Example: 0x3000000020000000100000004000000030000000200000001
	Timelocks string `json:"timelocks"`

	// Token Token to receive on specific chain
	//
	// Example: 0xdAC17F958D2ee523a2206206994597C13D831ec7
	Token string `json:"token"`
}

// LimitOrderV4StructOutput defines model for LimitOrderV4StructOutput.
type LimitOrderV4StructOutput struct {
	// Maker Maker address
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FA
	Maker string `json:"maker"`

	// MakerAsset Maker asset address
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FA
	MakerAsset  string `json:"makerAsset"`
	MakerTraits string `json:"makerTraits"`

	// MakingAmount Amount of the maker asset
	//
	// Example: 100000000000000000
	MakingAmount string `json:"makingAmount"`

	// Receiver Receiver address
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FA
	Receiver string `json:"receiver"`
	Salt     string `json:"salt"`

	// TakerAsset Taker asset address
	//
	// Example: 0x995BE1CA945174D5bA75410C1E658a41eB13a2FA
	TakerAsset string `json:"takerAsset"`

	// TakingAmount Amount of the taker asset
	//
	// Example: 100000000000000000
	TakingAmount string `json:"takingAmount"`
}

// Meta defines model for Meta.
type Meta struct {
	CurrentPage  float32 `json:"currentPage"`
	ItemsPerPage float32 `json:"itemsPerPage"`
	TotalItems   float32 `json:"totalItems"`
	TotalPages   float32 `json:"totalPages"`
}

// OrdersByHashesInput defines model for OrdersByHashesInput.
type OrdersByHashesInput struct {
	// OrderHashes Example: ["0x10ea5bd12b2d04566e175de24c2df41a058bf16df4af3eb2fb9bff38a9da98e9","0x20ea5bd12b2d04566e175de24c2df41a058bf16df4af3eb2fb9bff38a9da98e8","0x30ea5bd12b2d04566e175de24c2df41a058bf16df4af3eb2fb9bff38a9da98e7","0x40ea5bd12b2d04566e175de24c2df41a058bf16df4af3eb2fb9bff38a9da98e6"]
	OrderHashes []string `json:"orderHashes"`
}

// PublicSecret defines model for PublicSecret.
type PublicSecret struct {
	DstImmutables Immutables `json:"dstImmutables"`

	// Idx Sequence number of secrets
	//
	// Example: 1
	Idx float32 `json:"idx"`

	// Secret Public secret to perform a withdrawal
	//
	// Example: 0xdb475911f2d1c5df6b1fb959777ddd01c89d881175a3b9693ec884f18dcb5734
	Secret        string     `json:"secret"`
	SrcImmutables Immutables `json:"srcImmutables"`
}

// ReadyToAcceptSecretFill defines model for ReadyToAcceptSecretFill.
type ReadyToAcceptSecretFill struct {
	// DstEscrowDeployTxHash Transaction hash where the destination chain escrow was deployed
	DstEscrowDeployTxHash string `json:"dstEscrowDeployTxHash"`

	// Idx Sequence number of secrets for submission
	Idx float32 `json:"idx"`

	// SrcEscrowDeployTxHash Transaction hash where the source chain escrow was deployed
	SrcEscrowDeployTxHash string `json:"srcEscrowDeployTxHash"`
}

// ReadyToAcceptSecretFills defines model for ReadyToAcceptSecretFills.
type ReadyToAcceptSecretFills struct {
	// Fills Fills that are ready to accept secrets from the client
	Fills []ReadyToAcceptSecretFill `json:"fills"`
}

// ReadyToAcceptSecretFillsForAllOrders defines model for ReadyToAcceptSecretFillsForAllOrders.
type ReadyToAcceptSecretFillsForAllOrders struct {
	// Orders Fills that are ready to accept secrets from the client for all orders
	Orders []ReadyToAcceptSecretFillsForOrder `json:"orders"`
}

// ReadyToAcceptSecretFillsForOrder defines model for ReadyToAcceptSecretFillsForOrder.
type ReadyToAcceptSecretFillsForOrder struct {
	// Fills Fills that are ready to accept secrets from the client
	Fills []ReadyToAcceptSecretFill `json:"fills"`

	// MakerAddress Maker address
	//
	// Example: 0x496755a88564d8ded6759dff0252d3e6c3ef1fe42b4fa1bbc3f03bd2674f1079
	MakerAddress string `json:"makerAddress"`

	// OrderHash Order hash
	//
	// Example: 0x496755a88564d8ded6759dff0252d3e6c3ef1fe42b4fa1bbc3f03bd2674f1078
	OrderHash string `json:"orderHash"`
}

// ReadyToExecutePublicAction defines model for ReadyToExecutePublicAction.
type ReadyToExecutePublicAction struct {
	// Action Example: withdraw
	Action ReadyToExecutePublicActionAction `json:"action"`

	// ChainId Execute action on this chain
	//
	// Example: 1
	ChainId int `json:"chainId"`

	// Escrow Escrow's address to perform public action
	//
	// Example: 0xf1325353e081023520d44b7a24f72905ada3a080
	Escrow     string     `json:"escrow"`
	Immutables Immutables `json:"immutables"`

	// Secret Presented only for withdraw action
	//
	// Example: 0x496755a88564d8ded6759dff0252d3e6c3ef1fe42b4fa1bbc3f03bd2674f1078
	Secret string `json:"secret,omitempty"`
}

// ReadyToExecutePublicActionAction Example: withdraw
type ReadyToExecutePublicActionAction string

// ReadyToExecutePublicActionsOutput defines model for ReadyToExecutePublicActionsOutput.
type ReadyToExecutePublicActionsOutput struct {
	// Actions Actions allowed to be performed on public timelock periods
	Actions []ReadyToExecutePublicAction `json:"actions"`
}

// ResolverDataOutput defines model for ResolverDataOutput.
type ResolverDataOutput struct {
	// OrderType Type of the order: enabled or disabled partial fills
	//
	// Example: SingleFill
	OrderType ResolverDataOutputOrderType `json:"orderType"`

	// SecretHashes keccak256(secret(idx))[]
	//
	// Example: ["0x2048b38093dc53876b2bbd230ee8999791153db01de425112f449d018094e116","0x7972c1498893bb9b88baddc9decb78d8defdcc7a182a72edd8724498c75f088d","0x6d5b8f0b1f8a28564ff65e5f9c4d8a8a6babfb318bca6ecc9d872a3abe8a4ea0"]
	SecretHashes [][]interface{} `json:"secretHashes,omitempty"`

	// Secrets The data required for order withdraw and cancel
	Secrets []PublicSecret `json:"secrets"`
}

// ResolverDataOutputOrderType Type of the order: enabled or disabled partial fills
//
// Example: SingleFill
type ResolverDataOutputOrderType string

// OrderApiControllerGetActiveOrdersParams defines parameters for OrderApiControllerGetActiveOrders.
type OrderApiControllerGetActiveOrdersParams struct {
	// Page Pagination step, default: 1 (page = offset / limit)
	Page float32 `url:"page,omitempty" json:"page,omitempty"`

	// Limit Number of active orders to receive (default: 100, max: 500)
	Limit float32 `url:"limit,omitempty" json:"limit,omitempty"`

	// SrcChain Source chain of cross chain
	SrcChain int `url:"srcChain,omitempty" json:"srcChain,omitempty"`

	// DstChain Destination chain of cross chain
	DstChain int `url:"dstChain,omitempty" json:"dstChain,omitempty"`
}

// OrderApiControllerGetSettlementContractParams defines parameters for OrderApiControllerGetSettlementContract.
type OrderApiControllerGetSettlementContractParams struct {
	// ChainId Chain ID
	ChainId int `url:"chainId,omitempty" json:"chainId,omitempty"`
}

// OrderApiControllerGetOrdersByMakerParams defines parameters for OrderApiControllerGetOrdersByMaker.
type OrderApiControllerGetOrdersByMakerParams struct {
	// Page Pagination step, default: 1 (page = offset / limit)
	Page float32 `url:"page,omitempty" json:"page,omitempty"`

	// Limit Number of active orders to receive (default: 100, max: 500)
	Limit float32 `url:"limit,omitempty" json:"limit,omitempty"`

	// TimestampFrom timestampFrom in milliseconds for interval [timestampFrom, timestampTo)
	TimestampFrom float32 `url:"timestampFrom,omitempty" json:"timestampFrom,omitempty"`

	// TimestampTo timestampTo in milliseconds for interval [timestampFrom, timestampTo)
	TimestampTo float32 `url:"timestampTo,omitempty" json:"timestampTo,omitempty"`

	// SrcToken Find history by the given source token
	SrcToken string `url:"srcToken,omitempty" json:"srcToken,omitempty"`

	// DstToken Find history by the given destination token
	DstToken string `url:"dstToken,omitempty" json:"dstToken,omitempty"`

	// WithToken Find history items by source or destination token
	WithToken string `url:"withToken,omitempty" json:"withToken,omitempty"`

	// DstChainId Destination chain of cross chain
	DstChainId int `url:"dstChainId,omitempty" json:"dstChainId,omitempty"`

	// SrcChainId Source chain of cross chain
	SrcChainId int `url:"srcChainId,omitempty" json:"srcChainId,omitempty"`

	// ChainId chainId for looking by dstChainId == chainId OR srcChainId == chainId
	ChainId int `url:"chainId,omitempty" json:"chainId,omitempty"`
}

// OrderApiControllerGetOrdersByOrderHashesJSONRequestBody defines body for OrderApiControllerGetOrdersByOrderHashes for application/json ContentType.
type OrderApiControllerGetOrdersByOrderHashesJSONRequestBody = OrdersByHashesInput
