// Package fusion provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fusion

// Defines values for SubmitOrder400JSONResponseBodyError.
const (
	SubmitOrder400JSONResponseBodyErrorBadRequest SubmitOrder400JSONResponseBodyError = "Bad Request"
)

// Valid indicates whether the value is a known member of the SubmitOrder400JSONResponseBodyError enum.
func (e SubmitOrder400JSONResponseBodyError) Valid() bool {
	switch e {
	case SubmitOrder400JSONResponseBodyErrorBadRequest:
		return true
	default:
		return false
	}
}

// Defines values for SubmitOrder400JSONResponseBodyStatusCode.
const (
	SubmitOrder400JSONResponseBodyStatusCodeN400 SubmitOrder400JSONResponseBodyStatusCode = 400
)

// Valid indicates whether the value is a known member of the SubmitOrder400JSONResponseBodyStatusCode enum.
func (e SubmitOrder400JSONResponseBodyStatusCode) Valid() bool {
	switch e {
	case SubmitOrder400JSONResponseBodyStatusCodeN400:
		return true
	default:
		return false
	}
}

// Defines values for SubmitManyOrders400JSONResponseBodyError.
const (
	SubmitManyOrders400JSONResponseBodyErrorBadRequest SubmitManyOrders400JSONResponseBodyError = "Bad Request"
)

// Valid indicates whether the value is a known member of the SubmitManyOrders400JSONResponseBodyError enum.
func (e SubmitManyOrders400JSONResponseBodyError) Valid() bool {
	switch e {
	case SubmitManyOrders400JSONResponseBodyErrorBadRequest:
		return true
	default:
		return false
	}
}

// Defines values for SubmitManyOrders400JSONResponseBodyStatusCode.
const (
	SubmitManyOrders400JSONResponseBodyStatusCodeN400 SubmitManyOrders400JSONResponseBodyStatusCode = 400
)

// Valid indicates whether the value is a known member of the SubmitManyOrders400JSONResponseBodyStatusCode enum.
func (e SubmitManyOrders400JSONResponseBodyStatusCode) Valid() bool {
	switch e {
	case SubmitManyOrders400JSONResponseBodyStatusCodeN400:
		return true
	default:
		return false
	}
}

// OrderInput defines model for OrderInput.
type OrderInput struct {
	// Maker An address of the maker (wallet or contract address)
	Maker string `json:"maker"`

	// MakerAsset Address of the maker asset
	MakerAsset string `json:"makerAsset"`

	// MakerTraits Includes some flags like, allow multiple fills, is partial fill allowed or not, price improvement, nonce, deadline etc
	MakerTraits string `json:"makerTraits,omitempty"`

	// MakingAmount Order maker's token amount
	MakingAmount string `json:"makingAmount"`

	// Receiver An address of the wallet or contract who will receive filled amount
	Receiver string `json:"receiver,omitempty"`
	Salt     string `json:"salt"`

	// TakerAsset Address of the taker asset
	TakerAsset string `json:"takerAsset"`

	// TakingAmount Order taker's token amount
	TakingAmount string `json:"takingAmount"`
}

// SignedOrderInput defines model for SignedOrderInput.
type SignedOrderInput struct {
	// Extension An interaction call data. ABI encoded set of makerAssetSuffix, takerAssetSuffix, makingAmountGetter, takingAmountGetter, predicate, permit, preInteraction, postInteraction.Lowest 160 bits of the order salt must be equal to the lowest 160 bits of the extension hash
	Extension string     `json:"extension,omitempty"`
	Order     OrderInput `json:"order"`

	// QuoteId Quote id of the quote with presets
	QuoteId string `json:"quoteId"`

	// Signature Signature of the gasless order typed data (using signTypedData_v4)
	Signature string `json:"signature"`
}

// SubmitOrder400JSONResponseBodyError defines parameters for SubmitOrder.
type SubmitOrder400JSONResponseBodyError string

// SubmitOrder400JSONResponseBodyStatusCode defines parameters for SubmitOrder.
type SubmitOrder400JSONResponseBodyStatusCode int

// SubmitManyOrdersJSONBody defines parameters for SubmitManyOrders.
type SubmitManyOrdersJSONBody = []SignedOrderInput

// SubmitManyOrders400JSONResponseBodyError defines parameters for SubmitManyOrders.
type SubmitManyOrders400JSONResponseBodyError string

// SubmitManyOrders400JSONResponseBodyStatusCode defines parameters for SubmitManyOrders.
type SubmitManyOrders400JSONResponseBodyStatusCode int

// SubmitOrderJSONRequestBody defines body for SubmitOrder for application/json ContentType.
type SubmitOrderJSONRequestBody = SignedOrderInput

// SubmitManyOrdersJSONRequestBody defines body for SubmitManyOrders for application/json ContentType.
type SubmitManyOrdersJSONRequestBody = SubmitManyOrdersJSONBody
