// Package fusion provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fusion

// Defines values for RelayerControllerSubmit400JSONResponseBodyError.
const (
	RelayerControllerSubmit400JSONResponseBodyErrorBadRequest RelayerControllerSubmit400JSONResponseBodyError = "Bad Request"
)

// Valid indicates whether the value is a known member of the RelayerControllerSubmit400JSONResponseBodyError enum.
func (e RelayerControllerSubmit400JSONResponseBodyError) Valid() bool {
	switch e {
	case RelayerControllerSubmit400JSONResponseBodyErrorBadRequest:
		return true
	default:
		return false
	}
}

// Defines values for RelayerControllerSubmit400JSONResponseBodyStatusCode.
const (
	RelayerControllerSubmit400JSONResponseBodyStatusCodeN400 RelayerControllerSubmit400JSONResponseBodyStatusCode = 400
)

// Valid indicates whether the value is a known member of the RelayerControllerSubmit400JSONResponseBodyStatusCode enum.
func (e RelayerControllerSubmit400JSONResponseBodyStatusCode) Valid() bool {
	switch e {
	case RelayerControllerSubmit400JSONResponseBodyStatusCodeN400:
		return true
	default:
		return false
	}
}

// Defines values for RelayerControllerSubmitMany400JSONResponseBodyError.
const (
	RelayerControllerSubmitMany400JSONResponseBodyErrorBadRequest RelayerControllerSubmitMany400JSONResponseBodyError = "Bad Request"
)

// Valid indicates whether the value is a known member of the RelayerControllerSubmitMany400JSONResponseBodyError enum.
func (e RelayerControllerSubmitMany400JSONResponseBodyError) Valid() bool {
	switch e {
	case RelayerControllerSubmitMany400JSONResponseBodyErrorBadRequest:
		return true
	default:
		return false
	}
}

// Defines values for RelayerControllerSubmitMany400JSONResponseBodyStatusCode.
const (
	RelayerControllerSubmitMany400JSONResponseBodyStatusCodeN400 RelayerControllerSubmitMany400JSONResponseBodyStatusCode = 400
)

// Valid indicates whether the value is a known member of the RelayerControllerSubmitMany400JSONResponseBodyStatusCode enum.
func (e RelayerControllerSubmitMany400JSONResponseBodyStatusCode) Valid() bool {
	switch e {
	case RelayerControllerSubmitMany400JSONResponseBodyStatusCodeN400:
		return true
	default:
		return false
	}
}

// OrderInput defines model for OrderInput.
type OrderInput struct {
	// Maker An address of the maker (wallet or contract address)
	Maker string `json:"maker"`

	// MakerAsset Address of the maker asset
	MakerAsset string `json:"makerAsset"`

	// MakerTraits Includes some flags like, allow multiple fills, is partial fill allowed or not, price improvement, nonce, deadline etc
	MakerTraits string `json:"makerTraits,omitempty"`

	// MakingAmount Order maker's token amount
	MakingAmount string `json:"makingAmount"`

	// Receiver An address of the wallet or contract who will receive filled amount
	Receiver string `json:"receiver,omitempty"`
	Salt     string `json:"salt"`

	// TakerAsset Address of the taker asset
	TakerAsset string `json:"takerAsset"`

	// TakingAmount Order taker's token amount
	TakingAmount string `json:"takingAmount"`
}

// SignedOrderInput defines model for SignedOrderInput.
type SignedOrderInput struct {
	// Extension An interaction call data. ABI encoded set of makerAssetSuffix, takerAssetSuffix, makingAmountGetter, takingAmountGetter, predicate, permit, preInteraction, postInteraction.Lowest 160 bits of the order salt must be equal to the lowest 160 bits of the extension hash
	Extension string     `json:"extension,omitempty"`
	Order     OrderInput `json:"order"`

	// QuoteId Quote id of the quote with presets
	QuoteId string `json:"quoteId"`

	// Signature Signature of the gasless order typed data (using signTypedData_v4)
	Signature string `json:"signature"`
}

// RelayerControllerSubmit400JSONResponseBodyError defines parameters for RelayerControllerSubmit.
type RelayerControllerSubmit400JSONResponseBodyError string

// RelayerControllerSubmit400JSONResponseBodyStatusCode defines parameters for RelayerControllerSubmit.
type RelayerControllerSubmit400JSONResponseBodyStatusCode int

// RelayerControllerSubmitManyJSONBody defines parameters for RelayerControllerSubmitMany.
type RelayerControllerSubmitManyJSONBody = []SignedOrderInput

// RelayerControllerSubmitMany400JSONResponseBodyError defines parameters for RelayerControllerSubmitMany.
type RelayerControllerSubmitMany400JSONResponseBodyError string

// RelayerControllerSubmitMany400JSONResponseBodyStatusCode defines parameters for RelayerControllerSubmitMany.
type RelayerControllerSubmitMany400JSONResponseBodyStatusCode int

// RelayerControllerSubmitJSONRequestBody defines body for RelayerControllerSubmit for application/json ContentType.
type RelayerControllerSubmitJSONRequestBody = SignedOrderInput

// RelayerControllerSubmitManyJSONRequestBody defines body for RelayerControllerSubmitMany for application/json ContentType.
type RelayerControllerSubmitManyJSONRequestBody = RelayerControllerSubmitManyJSONBody
