// Package balances provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package balances

// AggregatedBalancesAndAllowancesResponse defines model for AggregatedBalancesAndAllowancesResponse.
type AggregatedBalancesAndAllowancesResponse = []struct {
	// Address Token contract address
	Address *string `json:"address,omitempty"`

	// Decimals Number of decimal places for the token
	Decimals *int `json:"decimals,omitempty"`

	// IsCustom Indicates if the token is custom or not
	IsCustom *bool `json:"isCustom,omitempty"`

	// LogoURI URL to the token logo image
	LogoURI *string `json:"logoURI,omitempty"`

	// Name Name of the token
	Name *string `json:"name,omitempty"`

	// Symbol Symbol of the token
	Symbol *string `json:"symbol,omitempty"`

	// Tags Additional tags for the token
	Tags *[]string `json:"tags,omitempty"`

	// Tracked Indicates if the token is tracked or not
	Tracked *bool `json:"tracked,omitempty"`

	// Type Type of token (e.g., 'ethereum', 'token')
	Type *string `json:"type,omitempty"`

	// Wallets Token balances and allowances for specific wallets
	Wallets *map[string]struct {
		// Allowance Allowance of the token for the wallet
		Allowance *string `json:"allowance,omitempty"`

		// Balance Balance of the token for the wallet
		Balance *string `json:"balance,omitempty"`
	} `json:"wallets,omitempty"`
}

// CustomTokensAndWalletsRequest defines model for CustomTokensAndWalletsRequest.
type CustomTokensAndWalletsRequest struct {
	// Tokens List of custom tokens
	//
	// Example: ["0xdac17f958d2ee523a2206206994597c13d831ec7"]
	Tokens []string `json:"tokens"`

	// Wallets List of wallets
	//
	// Example: ["0x7A1284A7fc85635B79BCd1C45089A0ddde05C7C0"]
	Wallets []string `json:"wallets"`
}

// CustomTokensRequest defines model for CustomTokensRequest.
type CustomTokensRequest struct {
	// Tokens List of custom tokens
	//
	// Example: ["0xdac17f958d2ee523a2206206994597c13d831ec7"]
	Tokens []string `json:"tokens"`
}

// GetAggregatedBalancesAndAllowancesParams defines parameters for GetAggregatedBalancesAndAllowances.
type GetAggregatedBalancesAndAllowancesParams struct {
	Wallets     []string `url:"wallets" json:"wallets"`
	FilterEmpty bool     `url:"filterEmpty" json:"filterEmpty"`
}

// GetCustomAllowancesJSONRequestBody defines body for GetCustomAllowances for application/json ContentType.
type GetCustomAllowancesJSONRequestBody = CustomTokensRequest

// GetCustomAllowancesAndBalancesJSONRequestBody defines body for GetCustomAllowancesAndBalances for application/json ContentType.
type GetCustomAllowancesAndBalancesJSONRequestBody = CustomTokensRequest

// GetBalancesByWalletsJSONRequestBody defines body for GetBalancesByWallets for application/json ContentType.
type GetBalancesByWalletsJSONRequestBody = CustomTokensAndWalletsRequest

// GetCustomBalancesJSONRequestBody defines body for GetCustomBalances for application/json ContentType.
type GetCustomBalancesJSONRequestBody = CustomTokensRequest
