// Package history provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package history

// Defines values for HistoryEventDtoRating.
const (
	Reliable HistoryEventDtoRating = "Reliable"
	Scam     HistoryEventDtoRating = "Scam"
)

// Defines values for HistoryEventDtoType.
const (
	FusionSwap  HistoryEventDtoType = "FusionSwap"
	LimitOrder  HistoryEventDtoType = "LimitOrder"
	Transaction HistoryEventDtoType = "Transaction"
)

// Defines values for TokenActionDtoDirection.
const (
	In   TokenActionDtoDirection = "In"
	On   TokenActionDtoDirection = "On"
	Out  TokenActionDtoDirection = "Out"
	Self TokenActionDtoDirection = "Self"
)

// Defines values for TransactionDetailsDtoChainId.
const (
	N1             TransactionDetailsDtoChainId = 1
	N10            TransactionDetailsDtoChainId = 10
	N100           TransactionDetailsDtoChainId = 100
	N1313161554e09 TransactionDetailsDtoChainId = 1.313161554e+09
	N137           TransactionDetailsDtoChainId = 137
	N250           TransactionDetailsDtoChainId = 250
	N324           TransactionDetailsDtoChainId = 324
	N42161         TransactionDetailsDtoChainId = 42161
	N43114         TransactionDetailsDtoChainId = 43114
	N45            TransactionDetailsDtoChainId = 45
	N56            TransactionDetailsDtoChainId = 56
	N8217          TransactionDetailsDtoChainId = 8217
	N8453          TransactionDetailsDtoChainId = 8453
)

// Defines values for TransactionDetailsDtoType.
const (
	AbiDecoded          TransactionDetailsDtoType = "AbiDecoded"
	Action              TransactionDetailsDtoType = "Action"
	AddLiquidity        TransactionDetailsDtoType = "AddLiquidity"
	AddOwner            TransactionDetailsDtoType = "AddOwner"
	Approve             TransactionDetailsDtoType = "Approve"
	BidNft              TransactionDetailsDtoType = "BidNft"
	Borrow              TransactionDetailsDtoType = "Borrow"
	Bridge              TransactionDetailsDtoType = "Bridge"
	Burn                TransactionDetailsDtoType = "Burn"
	BuyNft              TransactionDetailsDtoType = "BuyNft"
	Claim               TransactionDetailsDtoType = "Claim"
	CreateSafe          TransactionDetailsDtoType = "CreateSafe"
	DelegateVotePower   TransactionDetailsDtoType = "DelegateVotePower"
	DeployPool          TransactionDetailsDtoType = "DeployPool"
	DiscardVote         TransactionDetailsDtoType = "DiscardVote"
	LimitOrderCancel    TransactionDetailsDtoType = "LimitOrderCancel"
	LimitOrderCancelAll TransactionDetailsDtoType = "LimitOrderCancelAll"
	LimitOrderFill      TransactionDetailsDtoType = "LimitOrderFill"
	Multicall           TransactionDetailsDtoType = "Multicall"
	OfferSellNft        TransactionDetailsDtoType = "OfferSellNft"
	RegisterENSDomain   TransactionDetailsDtoType = "RegisterENSDomain"
	RemoveLiquidity     TransactionDetailsDtoType = "RemoveLiquidity"
	Repay               TransactionDetailsDtoType = "Repay"
	Revoke              TransactionDetailsDtoType = "Revoke"
	Stake               TransactionDetailsDtoType = "Stake"
	SwapExactInput      TransactionDetailsDtoType = "SwapExactInput"
	SwapExactOutput     TransactionDetailsDtoType = "SwapExactOutput"
	TraceDecoded        TransactionDetailsDtoType = "TraceDecoded"
	Transfer            TransactionDetailsDtoType = "Transfer"
	UnDelegateVotePower TransactionDetailsDtoType = "UnDelegateVotePower"
	Unstake             TransactionDetailsDtoType = "Unstake"
	Unwrap              TransactionDetailsDtoType = "Unwrap"
	Vote                TransactionDetailsDtoType = "Vote"
	Wrap                TransactionDetailsDtoType = "Wrap"
	WrappedTx           TransactionDetailsDtoType = "WrappedTx"
)

// HistoryEventDto defines model for HistoryEventDto.
type HistoryEventDto struct {
	Address string                `json:"address"`
	Details TransactionDetailsDto `json:"details"`
	Id      string                `json:"id"`
	Rating  HistoryEventDtoRating `json:"rating"`
	TimeMs  float32               `json:"timeMs"`
	Type    HistoryEventDtoType   `json:"type"`
}

// HistoryEventDtoRating defines model for HistoryEventDto.Rating.
type HistoryEventDtoRating string

// HistoryEventDtoType defines model for HistoryEventDto.Type.
type HistoryEventDtoType string

// HistoryResponseDto defines model for HistoryResponseDto.
type HistoryResponseDto struct {
	CacheCounter float32           `json:"cache_counter"`
	Items        []HistoryEventDto `json:"items"`
}

// TokenActionDto defines model for TokenActionDto.
type TokenActionDto struct {
	Address     string                  `json:"address"`
	Amount      map[string]interface{}  `json:"amount,omitempty"`
	Direction   TokenActionDtoDirection `json:"direction"`
	FromAddress string                  `json:"fromAddress"`
	Standard    string                  `json:"standard"`
	ToAddress   string                  `json:"toAddress"`
	TokenId     map[string]interface{}  `json:"tokenId,omitempty"`
}

// TokenActionDtoDirection defines model for TokenActionDto.Direction.
type TokenActionDtoDirection string

// TransactionDetailsDto defines model for TransactionDetailsDto.
type TransactionDetailsDto struct {
	BlockNumber  float32                      `json:"blockNumber"`
	BlockTimeSec float32                      `json:"blockTimeSec"`
	ChainId      TransactionDetailsDtoChainId `json:"chainId"`
	FeeInWei     string                       `json:"feeInWei"`
	FromAddress  string                       `json:"fromAddress"`
	Meta         *TransactionDetailsMetaDto   `json:"meta,omitempty"`
	Nonce        float32                      `json:"nonce"`
	OrderInBlock float32                      `json:"orderInBlock"`
	Status       string                       `json:"status"`
	ToAddress    string                       `json:"toAddress"`
	TokenActions []TokenActionDto             `json:"tokenActions"`
	TxHash       string                       `json:"txHash"`
	Type         TransactionDetailsDtoType    `json:"type"`
}

// TransactionDetailsDtoChainId defines model for TransactionDetailsDto.ChainId.
type TransactionDetailsDtoChainId int

// TransactionDetailsDtoType defines model for TransactionDetailsDto.Type.
type TransactionDetailsDtoType string

// TransactionDetailsMetaDto defines model for TransactionDetailsMetaDto.
type TransactionDetailsMetaDto struct {
	EnsDomainName       map[string]interface{} `json:"ensDomainName,omitempty"`
	FromChainId         map[string]interface{} `json:"fromChainId,omitempty"`
	Is1inchFusionSwap   map[string]interface{} `json:"is1inchFusionSwap,omitempty"`
	OrderFillPercentage map[string]interface{} `json:"orderFillPercentage,omitempty"`
	Protocol            map[string]interface{} `json:"protocol,omitempty"`
	SafeAddress         map[string]interface{} `json:"safeAddress,omitempty"`
	ToChainId           map[string]interface{} `json:"toChainId,omitempty"`
}

// V2RestApiControllerGetHistoryEventsByAddressParams defines parameters for V2RestApiControllerGetHistoryEventsByAddress.
type V2RestApiControllerGetHistoryEventsByAddressParams struct {
	// Limit Amount of events to return, default is 100, max is 10000
	Limit int `url:"limit,omitempty" json:"limit,omitempty"`

	// TokenAddress Token address used at event
	TokenAddress string `url:"tokenAddress,omitempty" json:"tokenAddress,omitempty"`

	// ChainId chainId
	ChainId int `url:"chainId,omitempty" json:"chainId,omitempty"`

	// ToTimestampMs To time at milliseconds
	ToTimestampMs int `url:"toTimestampMs,omitempty" json:"toTimestampMs,omitempty"`

	// FromTimestampMs From time at milliseconds
	FromTimestampMs int `url:"fromTimestampMs,omitempty" json:"fromTimestampMs,omitempty"`
}
