// Package history provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package history

// Defines values for HistoryEventDtoRating.
const (
	Reliable HistoryEventDtoRating = "Reliable"
	Scam     HistoryEventDtoRating = "Scam"
)

// Valid indicates whether the value is a known member of the HistoryEventDtoRating enum.
func (e HistoryEventDtoRating) Valid() bool {
	switch e {
	case Reliable:
		return true
	case Scam:
		return true
	default:
		return false
	}
}

// Defines values for HistoryEventDtoType.
const (
	FusionSwap  HistoryEventDtoType = "FusionSwap"
	LimitOrder  HistoryEventDtoType = "LimitOrder"
	Transaction HistoryEventDtoType = "Transaction"
)

// Valid indicates whether the value is a known member of the HistoryEventDtoType enum.
func (e HistoryEventDtoType) Valid() bool {
	switch e {
	case FusionSwap:
		return true
	case LimitOrder:
		return true
	case Transaction:
		return true
	default:
		return false
	}
}

// Defines values for TokenActionDtoDirection.
const (
	In   TokenActionDtoDirection = "In"
	On   TokenActionDtoDirection = "On"
	Out  TokenActionDtoDirection = "Out"
	Self TokenActionDtoDirection = "Self"
)

// Valid indicates whether the value is a known member of the TokenActionDtoDirection enum.
func (e TokenActionDtoDirection) Valid() bool {
	switch e {
	case In:
		return true
	case On:
		return true
	case Out:
		return true
	case Self:
		return true
	default:
		return false
	}
}

// Defines values for TransactionDetailsDtoChainId.
const (
	N1             TransactionDetailsDtoChainId = 1
	N10            TransactionDetailsDtoChainId = 10
	N100           TransactionDetailsDtoChainId = 100
	N1313161554e09 TransactionDetailsDtoChainId = 1.313161554e+09
	N137           TransactionDetailsDtoChainId = 137
	N250           TransactionDetailsDtoChainId = 250
	N324           TransactionDetailsDtoChainId = 324
	N42161         TransactionDetailsDtoChainId = 42161
	N43114         TransactionDetailsDtoChainId = 43114
	N45            TransactionDetailsDtoChainId = 45
	N56            TransactionDetailsDtoChainId = 56
	N8217          TransactionDetailsDtoChainId = 8217
	N8453          TransactionDetailsDtoChainId = 8453
)

// Valid indicates whether the value is a known member of the TransactionDetailsDtoChainId enum.
func (e TransactionDetailsDtoChainId) Valid() bool {
	switch e {
	case N1:
		return true
	case N10:
		return true
	case N100:
		return true
	case N1313161554e09:
		return true
	case N137:
		return true
	case N250:
		return true
	case N324:
		return true
	case N42161:
		return true
	case N43114:
		return true
	case N45:
		return true
	case N56:
		return true
	case N8217:
		return true
	case N8453:
		return true
	default:
		return false
	}
}

// Defines values for TransactionDetailsDtoType.
const (
	AbiDecoded          TransactionDetailsDtoType = "AbiDecoded"
	Action              TransactionDetailsDtoType = "Action"
	AddLiquidity        TransactionDetailsDtoType = "AddLiquidity"
	AddOwner            TransactionDetailsDtoType = "AddOwner"
	Approve             TransactionDetailsDtoType = "Approve"
	BidNft              TransactionDetailsDtoType = "BidNft"
	Borrow              TransactionDetailsDtoType = "Borrow"
	Bridge              TransactionDetailsDtoType = "Bridge"
	Burn                TransactionDetailsDtoType = "Burn"
	BuyNft              TransactionDetailsDtoType = "BuyNft"
	Claim               TransactionDetailsDtoType = "Claim"
	CreateSafe          TransactionDetailsDtoType = "CreateSafe"
	DelegateVotePower   TransactionDetailsDtoType = "DelegateVotePower"
	DeployPool          TransactionDetailsDtoType = "DeployPool"
	DiscardVote         TransactionDetailsDtoType = "DiscardVote"
	LimitOrderCancel    TransactionDetailsDtoType = "LimitOrderCancel"
	LimitOrderCancelAll TransactionDetailsDtoType = "LimitOrderCancelAll"
	LimitOrderFill      TransactionDetailsDtoType = "LimitOrderFill"
	Multicall           TransactionDetailsDtoType = "Multicall"
	OfferSellNft        TransactionDetailsDtoType = "OfferSellNft"
	RegisterENSDomain   TransactionDetailsDtoType = "RegisterENSDomain"
	RemoveLiquidity     TransactionDetailsDtoType = "RemoveLiquidity"
	Repay               TransactionDetailsDtoType = "Repay"
	Revoke              TransactionDetailsDtoType = "Revoke"
	Stake               TransactionDetailsDtoType = "Stake"
	SwapExactInput      TransactionDetailsDtoType = "SwapExactInput"
	SwapExactOutput     TransactionDetailsDtoType = "SwapExactOutput"
	TraceDecoded        TransactionDetailsDtoType = "TraceDecoded"
	Transfer            TransactionDetailsDtoType = "Transfer"
	UnDelegateVotePower TransactionDetailsDtoType = "UnDelegateVotePower"
	Unstake             TransactionDetailsDtoType = "Unstake"
	Unwrap              TransactionDetailsDtoType = "Unwrap"
	Vote                TransactionDetailsDtoType = "Vote"
	Wrap                TransactionDetailsDtoType = "Wrap"
	WrappedTx           TransactionDetailsDtoType = "WrappedTx"
)

// Valid indicates whether the value is a known member of the TransactionDetailsDtoType enum.
func (e TransactionDetailsDtoType) Valid() bool {
	switch e {
	case AbiDecoded:
		return true
	case Action:
		return true
	case AddLiquidity:
		return true
	case AddOwner:
		return true
	case Approve:
		return true
	case BidNft:
		return true
	case Borrow:
		return true
	case Bridge:
		return true
	case Burn:
		return true
	case BuyNft:
		return true
	case Claim:
		return true
	case CreateSafe:
		return true
	case DelegateVotePower:
		return true
	case DeployPool:
		return true
	case DiscardVote:
		return true
	case LimitOrderCancel:
		return true
	case LimitOrderCancelAll:
		return true
	case LimitOrderFill:
		return true
	case Multicall:
		return true
	case OfferSellNft:
		return true
	case RegisterENSDomain:
		return true
	case RemoveLiquidity:
		return true
	case Repay:
		return true
	case Revoke:
		return true
	case Stake:
		return true
	case SwapExactInput:
		return true
	case SwapExactOutput:
		return true
	case TraceDecoded:
		return true
	case Transfer:
		return true
	case UnDelegateVotePower:
		return true
	case Unstake:
		return true
	case Unwrap:
		return true
	case Vote:
		return true
	case Wrap:
		return true
	case WrappedTx:
		return true
	default:
		return false
	}
}

// HistoryEventDto defines model for HistoryEventDto.
type HistoryEventDto struct {
	// Address Example: 0x266E77cE9034a023056ea2845CB6A20517F6FDB7
	Address string                `json:"address"`
	Details TransactionDetailsDto `json:"details"`

	// Id Example: 7279741913753607
	Id string `json:"id"`

	// Rating Example: Reliable
	Rating HistoryEventDtoRating `json:"rating"`

	// TimeMs Example: 1694754179096
	TimeMs float32 `json:"timeMs"`

	// Type Example: Transaction
	Type HistoryEventDtoType `json:"type"`
}

// HistoryEventDtoRating Example: Reliable
type HistoryEventDtoRating string

// HistoryEventDtoType Example: Transaction
type HistoryEventDtoType string

// HistoryResponseDto defines model for HistoryResponseDto.
type HistoryResponseDto struct {
	CacheCounter float32           `json:"cache_counter"`
	Items        []HistoryEventDto `json:"items"`
}

// TokenActionDto defines model for TokenActionDto.
type TokenActionDto struct {
	// Address Example: 0xc944e90c64b2c07662a292be6244bdf05cda44a7
	Address string `json:"address"`

	// Amount Example: 291000000000
	Amount map[string]interface{} `json:"amount,omitempty"`

	// Direction Example: Out
	Direction TokenActionDtoDirection `json:"direction"`

	// FromAddress Example: 0x266e77ce9034a023056ea2845cb6a20517f6fdb7
	FromAddress string `json:"fromAddress"`

	// Standard Example: ERC20
	Standard string `json:"standard"`

	// ToAddress Example: 0x03f7724180aa6b939894b5ca4314783b0b36b329
	ToAddress string `json:"toAddress"`

	// TokenId Example: 0x03f7724180aa6b939894b5ca4314783b0b36b329
	TokenId map[string]interface{} `json:"tokenId,omitempty"`
}

// TokenActionDtoDirection Example: Out
type TokenActionDtoDirection string

// TransactionDetailsDto defines model for TransactionDetailsDto.
type TransactionDetailsDto struct {
	// BlockNumber Example: 18182982
	BlockNumber float32 `json:"blockNumber"`

	// BlockTimeSec Example: 1695283931
	BlockTimeSec float32 `json:"blockTimeSec"`

	// ChainId Example: 1
	ChainId TransactionDetailsDtoChainId `json:"chainId"`

	// FeeInWei Example: 378906276289230
	FeeInWei string `json:"feeInWei"`

	// FromAddress Example: 0x266e77ce9034a023056ea2845cb6a20517f6fdb7
	FromAddress string                    `json:"fromAddress"`
	Meta        TransactionDetailsMetaDto `json:"meta,omitempty"`

	// Nonce Example: 5
	Nonce float32 `json:"nonce"`

	// OrderInBlock Example: 2
	OrderInBlock float32 `json:"orderInBlock"`

	// Status Example: Completed
	Status string `json:"status"`

	// ToAddress Example: 0xc944e90c64b2c07662a292be6244bdf05cda44a7
	ToAddress    string           `json:"toAddress"`
	TokenActions []TokenActionDto `json:"tokenActions"`

	// TxHash Example: 0xdd87fbd093714d493ba53c000e4222b500e622500eeceaae9d4c4c5111ffbbfc
	TxHash string `json:"txHash"`

	// Type Example: Transfer
	Type TransactionDetailsDtoType `json:"type"`
}

// TransactionDetailsDtoChainId Example: 1
type TransactionDetailsDtoChainId int

// TransactionDetailsDtoType Example: Transfer
type TransactionDetailsDtoType string

// TransactionDetailsMetaDto defines model for TransactionDetailsMetaDto.
type TransactionDetailsMetaDto struct {
	// EnsDomainName Example: usd.eth
	EnsDomainName map[string]interface{} `json:"ensDomainName,omitempty"`

	// FromChainId Example: 56
	FromChainId map[string]interface{} `json:"fromChainId,omitempty"`

	// Is1inchFusionSwap Example: true
	Is1inchFusionSwap map[string]interface{} `json:"is1inchFusionSwap,omitempty"`

	// OrderFillPercentage Example: 2
	OrderFillPercentage map[string]interface{} `json:"orderFillPercentage,omitempty"`

	// Protocol Example: Gnosis
	Protocol map[string]interface{} `json:"protocol,omitempty"`

	// SafeAddress Example: 0x34391448368ae60aa7dc12dc309c4ef674a06d7f
	SafeAddress map[string]interface{} `json:"safeAddress,omitempty"`

	// ToChainId Example: 1
	ToChainId map[string]interface{} `json:"toChainId,omitempty"`
}

// GetHistoryEventsByAddressParams defines parameters for GetHistoryEventsByAddress.
type GetHistoryEventsByAddressParams struct {
	// Limit Amount of events to return, default is 100, max is 10000
	Limit int `url:"limit,omitempty" json:"limit,omitempty"`

	// TokenAddress Token address used at event
	TokenAddress string `url:"tokenAddress,omitempty" json:"tokenAddress,omitempty"`

	// ChainId chainId
	ChainId int `url:"chainId,omitempty" json:"chainId,omitempty"`

	// ToTimestampMs To time at milliseconds
	ToTimestampMs int `url:"toTimestampMs,omitempty" json:"toTimestampMs,omitempty"`

	// FromTimestampMs From time at milliseconds
	FromTimestampMs int `url:"fromTimestampMs,omitempty" json:"fromTimestampMs,omitempty"`
}
