// Package fusion provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package fusion

// OrderInput defines model for OrderInput.
type OrderInput struct {
	// AllowedSender An address of the settlement contract
	AllowedSender *string `json:"allowedSender,omitempty"`

	// Interactions An interaction call data. ABI encoded set of makerAssetData, takerAssetData, getMakingAmount, getTakingAmount, predicate, permit, preInteraction, postInteraction
	Interactions *string `json:"interactions,omitempty"`

	// Maker An address of the maker (wallet or contract address)
	Maker string `json:"maker"`

	// MakerAsset Address of the maker asset
	MakerAsset string `json:"makerAsset"`

	// MakingAmount Order maker's token amount
	MakingAmount string `json:"makingAmount"`

	// Offsets Merged offsets of each field in interactions
	Offsets *string `json:"offsets,omitempty"`

	// Receiver An address of the wallet or contract who will receive filled amount
	Receiver *string `json:"receiver,omitempty"`

	// Salt Contains of auction start time, auction duration, initial rate bump, fee and some unique value
	Salt string `json:"salt"`

	// TakerAsset Address of the taker asset
	TakerAsset string `json:"takerAsset"`

	// TakingAmount Order taker's token amount
	TakingAmount string `json:"takingAmount"`
}

// SignedOrderInput defines model for SignedOrderInput.
type SignedOrderInput struct {
	// Order Gasless order data
	Order OrderInput `json:"order"`

	// QuoteId Quote id of the quote with presets
	QuoteId string `json:"quoteId"`

	// Signature Signature of the gasless order typed data (using signTypedData_v4)
	Signature string `json:"signature"`
}

// RelayerControllerSubmitManyJSONBody defines parameters for RelayerControllerSubmitMany.
type RelayerControllerSubmitManyJSONBody = []SignedOrderInput

// RelayerControllerSubmitJSONRequestBody defines body for RelayerControllerSubmit for application/json ContentType.
type RelayerControllerSubmitJSONRequestBody = SignedOrderInput

// RelayerControllerSubmitManyJSONRequestBody defines body for RelayerControllerSubmitMany for application/json ContentType.
type RelayerControllerSubmitManyJSONRequestBody = RelayerControllerSubmitManyJSONBody
