// Package fusion provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package fusion

import (
	"time"
)

// ActiveOrdersOutput defines model for ActiveOrdersOutput.
type ActiveOrdersOutput struct {
	AuctionEndDate   time.Time `json:"auctionEndDate"`
	AuctionStartDate time.Time `json:"auctionStartDate"`
	Deadline         time.Time `json:"deadline"`

	// OrderHash i.e 0x806039f5149065924ad52de616b50abff488c986716d052e9c160887bc09e559
	OrderHash string `json:"orderHash"`

	// Signature i.e 0x38de7c8c406c8668eec947d59679028c068735e56c8a41bcc5b3dc2d2229dec258424e0f06b189d2b87f9f3d9cdd9edcb7b3be4108bd8605d052c20c84e65ad61c
	Signature string `json:"signature"`
}

// GetActiveOrdersOutput defines model for GetActiveOrdersOutput.
type GetActiveOrdersOutput struct {
	Items []ActiveOrdersOutput `json:"items"`
	Meta  Meta                 `json:"meta"`
}

// Meta defines model for Meta.
type Meta struct {
	CurrentPage  float32 `json:"currentPage"`
	ItemsPerPage float32 `json:"itemsPerPage"`
	TotalItems   float32 `json:"totalItems"`
	TotalPages   float32 `json:"totalPages"`
}

// SettlementAddressOutput defines model for SettlementAddressOutput.
type SettlementAddressOutput struct {
	// Address actual settlement contract address
	Address string `json:"address"`
}

// OrderApiControllerGetActiveOrdersParams defines parameters for OrderApiControllerGetActiveOrders.
type OrderApiControllerGetActiveOrdersParams struct {
	// Page Pagination step, default: 1 (page = offset / limit)
	Page *float32 `url:"page,omitempty" json:"page,omitempty"`

	// Limit Number of active orders to receive (default: 100, max: 500)
	Limit *float32 `url:"limit,omitempty" json:"limit,omitempty"`
}
