// Package fusion provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package fusion

// AuctionPointClass defines model for AuctionPointClass.
type AuctionPointClass struct {
	Coefficient float32 `json:"coefficient"`
	Delay       float32 `json:"delay"`
}

// CustomPresetInput defines model for CustomPresetInput.
type CustomPresetInput struct {
	AuctionDuration    float32   `json:"auctionDuration"`
	AuctionEndAmount   string    `json:"auctionEndAmount"`
	AuctionStartAmount string    `json:"auctionStartAmount"`
	Points             *[]string `json:"points,omitempty"`
}

// GetQuoteOutput defines model for GetQuoteOutput.
type GetQuoteOutput struct {
	// FeeToken Destination token address
	FeeToken        string `json:"feeToken"`
	FromTokenAmount string `json:"fromTokenAmount"`

	// Presets Various preset types which user can choose when using Fusion
	Presets QuotePresetsClass `json:"presets"`

	// QuoteId Current generated quote id, should be passed with order
	QuoteId string `json:"quoteId"`

	// SettlementAddress settlement contract address
	SettlementAddress string `json:"settlementAddress"`
	ToTokenAmount     string `json:"toTokenAmount"`

	// WhiteList current executors whitelist addresses
	WhiteList []string `json:"whiteList"`
}

// PresetClass defines model for PresetClass.
type PresetClass struct {
	AuctionDuration    float32             `json:"auctionDuration"`
	AuctionEndAmount   string              `json:"auctionEndAmount"`
	AuctionStartAmount string              `json:"auctionStartAmount"`
	BankFee            string              `json:"bankFee"`
	EstP               float32             `json:"estP"`
	InitialRateBump    float32             `json:"initialRateBump"`
	Points             []AuctionPointClass `json:"points"`
	StartAuctionIn     float32             `json:"startAuctionIn"`
	TokenFee           string              `json:"tokenFee"`
}

// QuotePresetsClass defines model for QuotePresetsClass.
type QuotePresetsClass struct {
	// Custom Custom preset type
	Custom *PresetClass `json:"custom,omitempty"`

	// Fast Fast preset type
	Fast PresetClass `json:"fast"`

	// Medium Medium preset type
	Medium PresetClass `json:"medium"`

	// Slow Slow preset type
	Slow PresetClass `json:"slow"`

	// SlowNoSlippage Slow preset type with 0 slippage allowed
	SlowNoSlippage PresetClass `json:"slow_no_slippage"`
}

// QuoterControllerGetQuoteParams defines parameters for QuoterControllerGetQuote.
type QuoterControllerGetQuoteParams struct {
	// FromTokenAddress Address of "FROM" token
	FromTokenAddress string `url:"fromTokenAddress" json:"fromTokenAddress"`

	// ToTokenAddress Address of "TO" token
	ToTokenAddress string `url:"toTokenAddress" json:"toTokenAddress"`

	// Amount Amount to take from "FROM" token to get "TO" token
	Amount float32 `url:"amount" json:"amount"`

	// WalletAddress An address of the wallet or contract who will create Fusion order
	WalletAddress string `url:"walletAddress" json:"walletAddress"`

	// EnableEstimate if enabled then get estimation from 1inch swap builder and generates quoteId, by default is false
	EnableEstimate bool `url:"enableEstimate" json:"enableEstimate"`

	// Fee fee in bps format, 1% is equal to 100bps
	Fee          *float32 `url:"fee,omitempty" json:"fee,omitempty"`
	IsLedgerLive bool     `url:"isLedgerLive" json:"isLedgerLive"`

	// Permit permit, user approval sign
	Permit *string `url:"permit,omitempty" json:"permit,omitempty"`
}

// QuoterControllerGetQuoteWithCustomPresetsParams defines parameters for QuoterControllerGetQuoteWithCustomPresets.
type QuoterControllerGetQuoteWithCustomPresetsParams struct {
	// FromTokenAddress Address of "FROM" token
	FromTokenAddress string `url:"fromTokenAddress" json:"fromTokenAddress"`

	// ToTokenAddress Address of "TO" token
	ToTokenAddress string `url:"toTokenAddress" json:"toTokenAddress"`

	// Amount Amount to take from "FROM" token to get "TO" token
	Amount float32 `url:"amount" json:"amount"`

	// WalletAddress An address of the wallet or contract who will create Fusion order
	WalletAddress string `url:"walletAddress" json:"walletAddress"`

	// EnableEstimate if enabled then get estimation from 1inch swap builder and generates quoteId, by default is false
	EnableEstimate bool `url:"enableEstimate" json:"enableEstimate"`

	// Fee fee in bps format, 1% is equal to 100bps
	Fee *float32 `url:"fee,omitempty" json:"fee,omitempty"`

	// Permit permit, user approval sign
	Permit *string `url:"permit,omitempty" json:"permit,omitempty"`
}

// QuoterControllerGetQuoteWithCustomPresetsJSONRequestBody defines body for QuoterControllerGetQuoteWithCustomPresets for application/json ContentType.
type QuoterControllerGetQuoteWithCustomPresetsJSONRequestBody = CustomPresetInput
