// Package gasprices provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package gasprices

// Eip1559GasPriceResponse defines model for Eip1559GasPriceResponse.
type Eip1559GasPriceResponse struct {
	BaseFee string                  `json:"baseFee"`
	High    Eip1559GasValueResponse `json:"high"`
	Instant Eip1559GasValueResponse `json:"instant"`
	Low     Eip1559GasValueResponse `json:"low"`
	Medium  Eip1559GasValueResponse `json:"medium"`
}

// Eip1559GasValueResponse defines model for Eip1559GasValueResponse.
type Eip1559GasValueResponse struct {
	MaxFeePerGas         string `json:"maxFeePerGas"`
	MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`
}
