// Package portfolio provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package portfolio

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TimeRange.
const (
	N1day   TimeRange = "1day"
	N1month TimeRange = "1month"
	N1week  TimeRange = "1week"
	N1year  TimeRange = "1year"
	N3years TimeRange = "3years"
)

// Valid indicates whether the value is a known member of the TimeRange enum.
func (e TimeRange) Valid() bool {
	switch e {
	case N1day:
		return true
	case N1month:
		return true
	case N1week:
		return true
	case N1year:
		return true
	case N3years:
		return true
	default:
		return false
	}
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// TimeRange defines model for TimeRange.
type TimeRange string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationError_Loc_Item `json:"loc"`
	Msg  string                     `json:"msg"`
	Type string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for ValidationError.Loc.0.
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for ValidationError.Loc.1.
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// GetCurrentValueParams defines parameters for GetCurrentValue.
type GetCurrentValueParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetProfitAndLossParams defines parameters for GetProfitAndLoss.
type GetProfitAndLossParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetValueChartParams defines parameters for GetValueChart.
type GetValueChartParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetTokensCurrentValueParams defines parameters for GetTokensCurrentValue.
type GetTokensCurrentValueParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetTokensDetailsParams defines parameters for GetTokensDetails.
type GetTokensDetailsParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetTokensProfitAndLossParams defines parameters for GetTokensProfitAndLoss.
type GetTokensProfitAndLossParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetProtocolsCurrentValueParams defines parameters for GetProtocolsCurrentValue.
type GetProtocolsCurrentValueParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetProtocolsDetailsParams defines parameters for GetProtocolsDetails.
type GetProtocolsDetailsParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetProtocolsProfitAndLossParams defines parameters for GetProtocolsProfitAndLoss.
type GetProtocolsProfitAndLossParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
