// Package portfolio provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package portfolio

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TimeRange.
const (
	N1day   TimeRange = "1day"
	N1month TimeRange = "1month"
	N1week  TimeRange = "1week"
	N1year  TimeRange = "1year"
	N3years TimeRange = "3years"
)

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// TimeRange defines model for TimeRange.
type TimeRange string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationError_Loc_Item `json:"loc"`
	Msg  string                     `json:"msg"`
	Type string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// GetCurrentValuePortfolioV4GeneralCurrentValueGetParams defines parameters for GetCurrentValuePortfolioV4GeneralCurrentValueGet.
type GetCurrentValuePortfolioV4GeneralCurrentValueGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetProfitAndLossPortfolioV4GeneralProfitAndLossGetParams defines parameters for GetProfitAndLossPortfolioV4GeneralProfitAndLossGet.
type GetProfitAndLossPortfolioV4GeneralProfitAndLossGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetValueChartPortfolioV4GeneralValueChartGetParams defines parameters for GetValueChartPortfolioV4GeneralValueChartGet.
type GetValueChartPortfolioV4GeneralValueChartGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetCurrentValuePortfolioV4OverviewErc20CurrentValueGetParams defines parameters for GetCurrentValuePortfolioV4OverviewErc20CurrentValueGet.
type GetCurrentValuePortfolioV4OverviewErc20CurrentValueGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetDetailsPortfolioV4OverviewErc20DetailsGetParams defines parameters for GetDetailsPortfolioV4OverviewErc20DetailsGet.
type GetDetailsPortfolioV4OverviewErc20DetailsGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetProfitAndLossPortfolioV4OverviewErc20ProfitAndLossGetParams defines parameters for GetProfitAndLossPortfolioV4OverviewErc20ProfitAndLossGet.
type GetProfitAndLossPortfolioV4OverviewErc20ProfitAndLossGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// GetCurrentValuePortfolioV4OverviewProtocolsCurrentValueGetParams defines parameters for GetCurrentValuePortfolioV4OverviewProtocolsCurrentValueGet.
type GetCurrentValuePortfolioV4OverviewProtocolsCurrentValueGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetDetailsPortfolioV4OverviewProtocolsDetailsGetParams defines parameters for GetDetailsPortfolioV4OverviewProtocolsDetailsGet.
type GetDetailsPortfolioV4OverviewProtocolsDetailsGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`
}

// GetProfitAndLossPortfolioV4OverviewProtocolsProfitAndLossGetParams defines parameters for GetProfitAndLossPortfolioV4OverviewProtocolsProfitAndLossGet.
type GetProfitAndLossPortfolioV4OverviewProtocolsProfitAndLossGetParams struct {
	// Addresses Addresses
	Addresses []string `url:"addresses" json:"addresses"`

	// ChainId Chain id or nothing
	ChainId int `url:"chain_id,omitempty" json:"chain_id,omitempty"`

	// Timerange Timerange
	Timerange *TimeRange `url:"timerange,omitempty" json:"timerange,omitempty"`
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
