// Package tokenprices provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package tokenprices

// Defines values for GetPricesRequestDtoCurrency.
const (
	GetPricesRequestDtoCurrencyUSD GetPricesRequestDtoCurrency = "USD"
)

// Defines values for ChainControllerWhitelistParamsCurrency.
const (
	ChainControllerWhitelistParamsCurrencyAED ChainControllerWhitelistParamsCurrency = "AED"
	ChainControllerWhitelistParamsCurrencyARS ChainControllerWhitelistParamsCurrency = "ARS"
	ChainControllerWhitelistParamsCurrencyAUD ChainControllerWhitelistParamsCurrency = "AUD"
	ChainControllerWhitelistParamsCurrencyBDT ChainControllerWhitelistParamsCurrency = "BDT"
	ChainControllerWhitelistParamsCurrencyBHD ChainControllerWhitelistParamsCurrency = "BHD"
	ChainControllerWhitelistParamsCurrencyBMD ChainControllerWhitelistParamsCurrency = "BMD"
	ChainControllerWhitelistParamsCurrencyBRL ChainControllerWhitelistParamsCurrency = "BRL"
	ChainControllerWhitelistParamsCurrencyCAD ChainControllerWhitelistParamsCurrency = "CAD"
	ChainControllerWhitelistParamsCurrencyCHF ChainControllerWhitelistParamsCurrency = "CHF"
	ChainControllerWhitelistParamsCurrencyCLP ChainControllerWhitelistParamsCurrency = "CLP"
	ChainControllerWhitelistParamsCurrencyCNY ChainControllerWhitelistParamsCurrency = "CNY"
	ChainControllerWhitelistParamsCurrencyCZK ChainControllerWhitelistParamsCurrency = "CZK"
	ChainControllerWhitelistParamsCurrencyDKK ChainControllerWhitelistParamsCurrency = "DKK"
	ChainControllerWhitelistParamsCurrencyEUR ChainControllerWhitelistParamsCurrency = "EUR"
	ChainControllerWhitelistParamsCurrencyGBP ChainControllerWhitelistParamsCurrency = "GBP"
	ChainControllerWhitelistParamsCurrencyHKD ChainControllerWhitelistParamsCurrency = "HKD"
	ChainControllerWhitelistParamsCurrencyHUF ChainControllerWhitelistParamsCurrency = "HUF"
	ChainControllerWhitelistParamsCurrencyIDR ChainControllerWhitelistParamsCurrency = "IDR"
	ChainControllerWhitelistParamsCurrencyILS ChainControllerWhitelistParamsCurrency = "ILS"
	ChainControllerWhitelistParamsCurrencyINR ChainControllerWhitelistParamsCurrency = "INR"
	ChainControllerWhitelistParamsCurrencyJPY ChainControllerWhitelistParamsCurrency = "JPY"
	ChainControllerWhitelistParamsCurrencyKRW ChainControllerWhitelistParamsCurrency = "KRW"
	ChainControllerWhitelistParamsCurrencyKWD ChainControllerWhitelistParamsCurrency = "KWD"
	ChainControllerWhitelistParamsCurrencyLKR ChainControllerWhitelistParamsCurrency = "LKR"
	ChainControllerWhitelistParamsCurrencyMMK ChainControllerWhitelistParamsCurrency = "MMK"
	ChainControllerWhitelistParamsCurrencyMXN ChainControllerWhitelistParamsCurrency = "MXN"
	ChainControllerWhitelistParamsCurrencyMYR ChainControllerWhitelistParamsCurrency = "MYR"
	ChainControllerWhitelistParamsCurrencyNGN ChainControllerWhitelistParamsCurrency = "NGN"
	ChainControllerWhitelistParamsCurrencyNOK ChainControllerWhitelistParamsCurrency = "NOK"
	ChainControllerWhitelistParamsCurrencyNZD ChainControllerWhitelistParamsCurrency = "NZD"
	ChainControllerWhitelistParamsCurrencyPHP ChainControllerWhitelistParamsCurrency = "PHP"
	ChainControllerWhitelistParamsCurrencyPKR ChainControllerWhitelistParamsCurrency = "PKR"
	ChainControllerWhitelistParamsCurrencyPLN ChainControllerWhitelistParamsCurrency = "PLN"
	ChainControllerWhitelistParamsCurrencyRUB ChainControllerWhitelistParamsCurrency = "RUB"
	ChainControllerWhitelistParamsCurrencySAR ChainControllerWhitelistParamsCurrency = "SAR"
	ChainControllerWhitelistParamsCurrencySEK ChainControllerWhitelistParamsCurrency = "SEK"
	ChainControllerWhitelistParamsCurrencySGD ChainControllerWhitelistParamsCurrency = "SGD"
	ChainControllerWhitelistParamsCurrencyTHB ChainControllerWhitelistParamsCurrency = "THB"
	ChainControllerWhitelistParamsCurrencyTRY ChainControllerWhitelistParamsCurrency = "TRY"
	ChainControllerWhitelistParamsCurrencyTWD ChainControllerWhitelistParamsCurrency = "TWD"
	ChainControllerWhitelistParamsCurrencyUAH ChainControllerWhitelistParamsCurrency = "UAH"
	ChainControllerWhitelistParamsCurrencyUSD ChainControllerWhitelistParamsCurrency = "USD"
	ChainControllerWhitelistParamsCurrencyVEF ChainControllerWhitelistParamsCurrency = "VEF"
	ChainControllerWhitelistParamsCurrencyVND ChainControllerWhitelistParamsCurrency = "VND"
	ChainControllerWhitelistParamsCurrencyZAR ChainControllerWhitelistParamsCurrency = "ZAR"
)

// Defines values for ChainControllerByAddressesParamsCurrency.
const (
	AED ChainControllerByAddressesParamsCurrency = "AED"
	ARS ChainControllerByAddressesParamsCurrency = "ARS"
	AUD ChainControllerByAddressesParamsCurrency = "AUD"
	BDT ChainControllerByAddressesParamsCurrency = "BDT"
	BHD ChainControllerByAddressesParamsCurrency = "BHD"
	BMD ChainControllerByAddressesParamsCurrency = "BMD"
	BRL ChainControllerByAddressesParamsCurrency = "BRL"
	CAD ChainControllerByAddressesParamsCurrency = "CAD"
	CHF ChainControllerByAddressesParamsCurrency = "CHF"
	CLP ChainControllerByAddressesParamsCurrency = "CLP"
	CNY ChainControllerByAddressesParamsCurrency = "CNY"
	CZK ChainControllerByAddressesParamsCurrency = "CZK"
	DKK ChainControllerByAddressesParamsCurrency = "DKK"
	EUR ChainControllerByAddressesParamsCurrency = "EUR"
	GBP ChainControllerByAddressesParamsCurrency = "GBP"
	HKD ChainControllerByAddressesParamsCurrency = "HKD"
	HUF ChainControllerByAddressesParamsCurrency = "HUF"
	IDR ChainControllerByAddressesParamsCurrency = "IDR"
	ILS ChainControllerByAddressesParamsCurrency = "ILS"
	INR ChainControllerByAddressesParamsCurrency = "INR"
	JPY ChainControllerByAddressesParamsCurrency = "JPY"
	KRW ChainControllerByAddressesParamsCurrency = "KRW"
	KWD ChainControllerByAddressesParamsCurrency = "KWD"
	LKR ChainControllerByAddressesParamsCurrency = "LKR"
	MMK ChainControllerByAddressesParamsCurrency = "MMK"
	MXN ChainControllerByAddressesParamsCurrency = "MXN"
	MYR ChainControllerByAddressesParamsCurrency = "MYR"
	NGN ChainControllerByAddressesParamsCurrency = "NGN"
	NOK ChainControllerByAddressesParamsCurrency = "NOK"
	NZD ChainControllerByAddressesParamsCurrency = "NZD"
	PHP ChainControllerByAddressesParamsCurrency = "PHP"
	PKR ChainControllerByAddressesParamsCurrency = "PKR"
	PLN ChainControllerByAddressesParamsCurrency = "PLN"
	RUB ChainControllerByAddressesParamsCurrency = "RUB"
	SAR ChainControllerByAddressesParamsCurrency = "SAR"
	SEK ChainControllerByAddressesParamsCurrency = "SEK"
	SGD ChainControllerByAddressesParamsCurrency = "SGD"
	THB ChainControllerByAddressesParamsCurrency = "THB"
	TRY ChainControllerByAddressesParamsCurrency = "TRY"
	TWD ChainControllerByAddressesParamsCurrency = "TWD"
	UAH ChainControllerByAddressesParamsCurrency = "UAH"
	USD ChainControllerByAddressesParamsCurrency = "USD"
	VEF ChainControllerByAddressesParamsCurrency = "VEF"
	VND ChainControllerByAddressesParamsCurrency = "VND"
	ZAR ChainControllerByAddressesParamsCurrency = "ZAR"
)

// CurrenciesResponseDto defines model for CurrenciesResponseDto.
type CurrenciesResponseDto struct {
	Codes []string `json:"codes"`
}

// GetPricesRequestDto defines model for GetPricesRequestDto.
type GetPricesRequestDto struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency *GetPricesRequestDtoCurrency `json:"currency,omitempty"`
	Tokens   []string                     `json:"tokens"`
}

// GetPricesRequestDtoCurrency If no currency provided, then price returned in native Wei
type GetPricesRequestDtoCurrency string

// ChainControllerWhitelistParams defines parameters for ChainControllerWhitelist.
type ChainControllerWhitelistParams struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency *ChainControllerWhitelistParamsCurrency `url:"currency,omitempty" json:"currency,omitempty"`
}

// ChainControllerWhitelistParamsCurrency defines parameters for ChainControllerWhitelist.
type ChainControllerWhitelistParamsCurrency string

// ChainControllerByAddressesParams defines parameters for ChainControllerByAddresses.
type ChainControllerByAddressesParams struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency *ChainControllerByAddressesParamsCurrency `url:"currency,omitempty" json:"currency,omitempty"`
}

// ChainControllerByAddressesParamsCurrency defines parameters for ChainControllerByAddresses.
type ChainControllerByAddressesParamsCurrency string

// ChainControllerByAddressesPostJSONRequestBody defines body for ChainControllerByAddressesPost for application/json ContentType.
type ChainControllerByAddressesPostJSONRequestBody = GetPricesRequestDto
