// Package spotprices provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package spotprices

// Defines values for GetPricesRequestDtoCurrency.
const (
	GetPricesRequestDtoCurrencyUSD GetPricesRequestDtoCurrency = "USD"
)

// Defines values for GetWhitelistedTokensPricesParamsCurrency.
const (
	GetWhitelistedTokensPricesParamsCurrencyAED GetWhitelistedTokensPricesParamsCurrency = "AED"
	GetWhitelistedTokensPricesParamsCurrencyARS GetWhitelistedTokensPricesParamsCurrency = "ARS"
	GetWhitelistedTokensPricesParamsCurrencyAUD GetWhitelistedTokensPricesParamsCurrency = "AUD"
	GetWhitelistedTokensPricesParamsCurrencyBDT GetWhitelistedTokensPricesParamsCurrency = "BDT"
	GetWhitelistedTokensPricesParamsCurrencyBHD GetWhitelistedTokensPricesParamsCurrency = "BHD"
	GetWhitelistedTokensPricesParamsCurrencyBMD GetWhitelistedTokensPricesParamsCurrency = "BMD"
	GetWhitelistedTokensPricesParamsCurrencyBRL GetWhitelistedTokensPricesParamsCurrency = "BRL"
	GetWhitelistedTokensPricesParamsCurrencyCAD GetWhitelistedTokensPricesParamsCurrency = "CAD"
	GetWhitelistedTokensPricesParamsCurrencyCHF GetWhitelistedTokensPricesParamsCurrency = "CHF"
	GetWhitelistedTokensPricesParamsCurrencyCLP GetWhitelistedTokensPricesParamsCurrency = "CLP"
	GetWhitelistedTokensPricesParamsCurrencyCNY GetWhitelistedTokensPricesParamsCurrency = "CNY"
	GetWhitelistedTokensPricesParamsCurrencyCZK GetWhitelistedTokensPricesParamsCurrency = "CZK"
	GetWhitelistedTokensPricesParamsCurrencyDKK GetWhitelistedTokensPricesParamsCurrency = "DKK"
	GetWhitelistedTokensPricesParamsCurrencyEUR GetWhitelistedTokensPricesParamsCurrency = "EUR"
	GetWhitelistedTokensPricesParamsCurrencyGBP GetWhitelistedTokensPricesParamsCurrency = "GBP"
	GetWhitelistedTokensPricesParamsCurrencyHKD GetWhitelistedTokensPricesParamsCurrency = "HKD"
	GetWhitelistedTokensPricesParamsCurrencyHUF GetWhitelistedTokensPricesParamsCurrency = "HUF"
	GetWhitelistedTokensPricesParamsCurrencyIDR GetWhitelistedTokensPricesParamsCurrency = "IDR"
	GetWhitelistedTokensPricesParamsCurrencyILS GetWhitelistedTokensPricesParamsCurrency = "ILS"
	GetWhitelistedTokensPricesParamsCurrencyINR GetWhitelistedTokensPricesParamsCurrency = "INR"
	GetWhitelistedTokensPricesParamsCurrencyJPY GetWhitelistedTokensPricesParamsCurrency = "JPY"
	GetWhitelistedTokensPricesParamsCurrencyKRW GetWhitelistedTokensPricesParamsCurrency = "KRW"
	GetWhitelistedTokensPricesParamsCurrencyKWD GetWhitelistedTokensPricesParamsCurrency = "KWD"
	GetWhitelistedTokensPricesParamsCurrencyLKR GetWhitelistedTokensPricesParamsCurrency = "LKR"
	GetWhitelistedTokensPricesParamsCurrencyMMK GetWhitelistedTokensPricesParamsCurrency = "MMK"
	GetWhitelistedTokensPricesParamsCurrencyMXN GetWhitelistedTokensPricesParamsCurrency = "MXN"
	GetWhitelistedTokensPricesParamsCurrencyMYR GetWhitelistedTokensPricesParamsCurrency = "MYR"
	GetWhitelistedTokensPricesParamsCurrencyNGN GetWhitelistedTokensPricesParamsCurrency = "NGN"
	GetWhitelistedTokensPricesParamsCurrencyNOK GetWhitelistedTokensPricesParamsCurrency = "NOK"
	GetWhitelistedTokensPricesParamsCurrencyNZD GetWhitelistedTokensPricesParamsCurrency = "NZD"
	GetWhitelistedTokensPricesParamsCurrencyPHP GetWhitelistedTokensPricesParamsCurrency = "PHP"
	GetWhitelistedTokensPricesParamsCurrencyPKR GetWhitelistedTokensPricesParamsCurrency = "PKR"
	GetWhitelistedTokensPricesParamsCurrencyPLN GetWhitelistedTokensPricesParamsCurrency = "PLN"
	GetWhitelistedTokensPricesParamsCurrencyRUB GetWhitelistedTokensPricesParamsCurrency = "RUB"
	GetWhitelistedTokensPricesParamsCurrencySAR GetWhitelistedTokensPricesParamsCurrency = "SAR"
	GetWhitelistedTokensPricesParamsCurrencySEK GetWhitelistedTokensPricesParamsCurrency = "SEK"
	GetWhitelistedTokensPricesParamsCurrencySGD GetWhitelistedTokensPricesParamsCurrency = "SGD"
	GetWhitelistedTokensPricesParamsCurrencyTHB GetWhitelistedTokensPricesParamsCurrency = "THB"
	GetWhitelistedTokensPricesParamsCurrencyTRY GetWhitelistedTokensPricesParamsCurrency = "TRY"
	GetWhitelistedTokensPricesParamsCurrencyTWD GetWhitelistedTokensPricesParamsCurrency = "TWD"
	GetWhitelistedTokensPricesParamsCurrencyUAH GetWhitelistedTokensPricesParamsCurrency = "UAH"
	GetWhitelistedTokensPricesParamsCurrencyUSD GetWhitelistedTokensPricesParamsCurrency = "USD"
	GetWhitelistedTokensPricesParamsCurrencyVEF GetWhitelistedTokensPricesParamsCurrency = "VEF"
	GetWhitelistedTokensPricesParamsCurrencyVND GetWhitelistedTokensPricesParamsCurrency = "VND"
	GetWhitelistedTokensPricesParamsCurrencyZAR GetWhitelistedTokensPricesParamsCurrency = "ZAR"
)

// Defines values for GetPricesForRequestedTokensParamsCurrency.
const (
	AED GetPricesForRequestedTokensParamsCurrency = "AED"
	ARS GetPricesForRequestedTokensParamsCurrency = "ARS"
	AUD GetPricesForRequestedTokensParamsCurrency = "AUD"
	BDT GetPricesForRequestedTokensParamsCurrency = "BDT"
	BHD GetPricesForRequestedTokensParamsCurrency = "BHD"
	BMD GetPricesForRequestedTokensParamsCurrency = "BMD"
	BRL GetPricesForRequestedTokensParamsCurrency = "BRL"
	CAD GetPricesForRequestedTokensParamsCurrency = "CAD"
	CHF GetPricesForRequestedTokensParamsCurrency = "CHF"
	CLP GetPricesForRequestedTokensParamsCurrency = "CLP"
	CNY GetPricesForRequestedTokensParamsCurrency = "CNY"
	CZK GetPricesForRequestedTokensParamsCurrency = "CZK"
	DKK GetPricesForRequestedTokensParamsCurrency = "DKK"
	EUR GetPricesForRequestedTokensParamsCurrency = "EUR"
	GBP GetPricesForRequestedTokensParamsCurrency = "GBP"
	HKD GetPricesForRequestedTokensParamsCurrency = "HKD"
	HUF GetPricesForRequestedTokensParamsCurrency = "HUF"
	IDR GetPricesForRequestedTokensParamsCurrency = "IDR"
	ILS GetPricesForRequestedTokensParamsCurrency = "ILS"
	INR GetPricesForRequestedTokensParamsCurrency = "INR"
	JPY GetPricesForRequestedTokensParamsCurrency = "JPY"
	KRW GetPricesForRequestedTokensParamsCurrency = "KRW"
	KWD GetPricesForRequestedTokensParamsCurrency = "KWD"
	LKR GetPricesForRequestedTokensParamsCurrency = "LKR"
	MMK GetPricesForRequestedTokensParamsCurrency = "MMK"
	MXN GetPricesForRequestedTokensParamsCurrency = "MXN"
	MYR GetPricesForRequestedTokensParamsCurrency = "MYR"
	NGN GetPricesForRequestedTokensParamsCurrency = "NGN"
	NOK GetPricesForRequestedTokensParamsCurrency = "NOK"
	NZD GetPricesForRequestedTokensParamsCurrency = "NZD"
	PHP GetPricesForRequestedTokensParamsCurrency = "PHP"
	PKR GetPricesForRequestedTokensParamsCurrency = "PKR"
	PLN GetPricesForRequestedTokensParamsCurrency = "PLN"
	RUB GetPricesForRequestedTokensParamsCurrency = "RUB"
	SAR GetPricesForRequestedTokensParamsCurrency = "SAR"
	SEK GetPricesForRequestedTokensParamsCurrency = "SEK"
	SGD GetPricesForRequestedTokensParamsCurrency = "SGD"
	THB GetPricesForRequestedTokensParamsCurrency = "THB"
	TRY GetPricesForRequestedTokensParamsCurrency = "TRY"
	TWD GetPricesForRequestedTokensParamsCurrency = "TWD"
	UAH GetPricesForRequestedTokensParamsCurrency = "UAH"
	USD GetPricesForRequestedTokensParamsCurrency = "USD"
	VEF GetPricesForRequestedTokensParamsCurrency = "VEF"
	VND GetPricesForRequestedTokensParamsCurrency = "VND"
	ZAR GetPricesForRequestedTokensParamsCurrency = "ZAR"
)

// CurrenciesResponseDto defines model for CurrenciesResponseDto.
type CurrenciesResponseDto struct {
	Codes []string `json:"codes"`
}

// GetPricesRequestDto defines model for GetPricesRequestDto.
type GetPricesRequestDto struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency GetPricesRequestDtoCurrency `json:"currency,omitempty"`
	Tokens   []string                    `json:"tokens"`
}

// GetPricesRequestDtoCurrency If no currency provided, then price returned in native Wei
type GetPricesRequestDtoCurrency string

// GetWhitelistedTokensPricesParams defines parameters for GetWhitelistedTokensPrices.
type GetWhitelistedTokensPricesParams struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency GetWhitelistedTokensPricesParamsCurrency `url:"currency,omitempty" json:"currency,omitempty"`
}

// GetWhitelistedTokensPricesParamsCurrency defines parameters for GetWhitelistedTokensPrices.
type GetWhitelistedTokensPricesParamsCurrency string

// GetPricesForRequestedTokensParams defines parameters for GetPricesForRequestedTokens.
type GetPricesForRequestedTokensParams struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency GetPricesForRequestedTokensParamsCurrency `url:"currency,omitempty" json:"currency,omitempty"`
}

// GetPricesForRequestedTokensParamsCurrency defines parameters for GetPricesForRequestedTokens.
type GetPricesForRequestedTokensParamsCurrency string

// GetPricesForRequestedTokensJSONRequestBody defines body for GetPricesForRequestedTokens for application/json ContentType.
type GetPricesForRequestedTokensJSONRequestBody = GetPricesRequestDto
