// Package spotprices provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package spotprices

// Defines values for GetPricesRequestDtoCurrency.
const (
	GetPricesRequestDtoCurrencyUSD GetPricesRequestDtoCurrency = "USD"
)

// Valid indicates whether the value is a known member of the GetPricesRequestDtoCurrency enum.
func (e GetPricesRequestDtoCurrency) Valid() bool {
	switch e {
	case GetPricesRequestDtoCurrencyUSD:
		return true
	default:
		return false
	}
}

// Defines values for GetWhitelistedTokensPricesParamsCurrency.
const (
	GetWhitelistedTokensPricesParamsCurrencyAED GetWhitelistedTokensPricesParamsCurrency = "AED"
	GetWhitelistedTokensPricesParamsCurrencyARS GetWhitelistedTokensPricesParamsCurrency = "ARS"
	GetWhitelistedTokensPricesParamsCurrencyAUD GetWhitelistedTokensPricesParamsCurrency = "AUD"
	GetWhitelistedTokensPricesParamsCurrencyBDT GetWhitelistedTokensPricesParamsCurrency = "BDT"
	GetWhitelistedTokensPricesParamsCurrencyBHD GetWhitelistedTokensPricesParamsCurrency = "BHD"
	GetWhitelistedTokensPricesParamsCurrencyBMD GetWhitelistedTokensPricesParamsCurrency = "BMD"
	GetWhitelistedTokensPricesParamsCurrencyBRL GetWhitelistedTokensPricesParamsCurrency = "BRL"
	GetWhitelistedTokensPricesParamsCurrencyCAD GetWhitelistedTokensPricesParamsCurrency = "CAD"
	GetWhitelistedTokensPricesParamsCurrencyCHF GetWhitelistedTokensPricesParamsCurrency = "CHF"
	GetWhitelistedTokensPricesParamsCurrencyCLP GetWhitelistedTokensPricesParamsCurrency = "CLP"
	GetWhitelistedTokensPricesParamsCurrencyCNY GetWhitelistedTokensPricesParamsCurrency = "CNY"
	GetWhitelistedTokensPricesParamsCurrencyCZK GetWhitelistedTokensPricesParamsCurrency = "CZK"
	GetWhitelistedTokensPricesParamsCurrencyDKK GetWhitelistedTokensPricesParamsCurrency = "DKK"
	GetWhitelistedTokensPricesParamsCurrencyEUR GetWhitelistedTokensPricesParamsCurrency = "EUR"
	GetWhitelistedTokensPricesParamsCurrencyGBP GetWhitelistedTokensPricesParamsCurrency = "GBP"
	GetWhitelistedTokensPricesParamsCurrencyHKD GetWhitelistedTokensPricesParamsCurrency = "HKD"
	GetWhitelistedTokensPricesParamsCurrencyHUF GetWhitelistedTokensPricesParamsCurrency = "HUF"
	GetWhitelistedTokensPricesParamsCurrencyIDR GetWhitelistedTokensPricesParamsCurrency = "IDR"
	GetWhitelistedTokensPricesParamsCurrencyILS GetWhitelistedTokensPricesParamsCurrency = "ILS"
	GetWhitelistedTokensPricesParamsCurrencyINR GetWhitelistedTokensPricesParamsCurrency = "INR"
	GetWhitelistedTokensPricesParamsCurrencyJPY GetWhitelistedTokensPricesParamsCurrency = "JPY"
	GetWhitelistedTokensPricesParamsCurrencyKRW GetWhitelistedTokensPricesParamsCurrency = "KRW"
	GetWhitelistedTokensPricesParamsCurrencyKWD GetWhitelistedTokensPricesParamsCurrency = "KWD"
	GetWhitelistedTokensPricesParamsCurrencyLKR GetWhitelistedTokensPricesParamsCurrency = "LKR"
	GetWhitelistedTokensPricesParamsCurrencyMMK GetWhitelistedTokensPricesParamsCurrency = "MMK"
	GetWhitelistedTokensPricesParamsCurrencyMXN GetWhitelistedTokensPricesParamsCurrency = "MXN"
	GetWhitelistedTokensPricesParamsCurrencyMYR GetWhitelistedTokensPricesParamsCurrency = "MYR"
	GetWhitelistedTokensPricesParamsCurrencyNGN GetWhitelistedTokensPricesParamsCurrency = "NGN"
	GetWhitelistedTokensPricesParamsCurrencyNOK GetWhitelistedTokensPricesParamsCurrency = "NOK"
	GetWhitelistedTokensPricesParamsCurrencyNZD GetWhitelistedTokensPricesParamsCurrency = "NZD"
	GetWhitelistedTokensPricesParamsCurrencyPHP GetWhitelistedTokensPricesParamsCurrency = "PHP"
	GetWhitelistedTokensPricesParamsCurrencyPKR GetWhitelistedTokensPricesParamsCurrency = "PKR"
	GetWhitelistedTokensPricesParamsCurrencyPLN GetWhitelistedTokensPricesParamsCurrency = "PLN"
	GetWhitelistedTokensPricesParamsCurrencyRUB GetWhitelistedTokensPricesParamsCurrency = "RUB"
	GetWhitelistedTokensPricesParamsCurrencySAR GetWhitelistedTokensPricesParamsCurrency = "SAR"
	GetWhitelistedTokensPricesParamsCurrencySEK GetWhitelistedTokensPricesParamsCurrency = "SEK"
	GetWhitelistedTokensPricesParamsCurrencySGD GetWhitelistedTokensPricesParamsCurrency = "SGD"
	GetWhitelistedTokensPricesParamsCurrencyTHB GetWhitelistedTokensPricesParamsCurrency = "THB"
	GetWhitelistedTokensPricesParamsCurrencyTRY GetWhitelistedTokensPricesParamsCurrency = "TRY"
	GetWhitelistedTokensPricesParamsCurrencyTWD GetWhitelistedTokensPricesParamsCurrency = "TWD"
	GetWhitelistedTokensPricesParamsCurrencyUAH GetWhitelistedTokensPricesParamsCurrency = "UAH"
	GetWhitelistedTokensPricesParamsCurrencyUSD GetWhitelistedTokensPricesParamsCurrency = "USD"
	GetWhitelistedTokensPricesParamsCurrencyVEF GetWhitelistedTokensPricesParamsCurrency = "VEF"
	GetWhitelistedTokensPricesParamsCurrencyVND GetWhitelistedTokensPricesParamsCurrency = "VND"
	GetWhitelistedTokensPricesParamsCurrencyZAR GetWhitelistedTokensPricesParamsCurrency = "ZAR"
)

// Valid indicates whether the value is a known member of the GetWhitelistedTokensPricesParamsCurrency enum.
func (e GetWhitelistedTokensPricesParamsCurrency) Valid() bool {
	switch e {
	case GetWhitelistedTokensPricesParamsCurrencyAED:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyARS:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyAUD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyBDT:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyBHD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyBMD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyBRL:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyCAD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyCHF:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyCLP:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyCNY:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyCZK:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyDKK:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyEUR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyGBP:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyHKD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyHUF:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyIDR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyILS:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyINR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyJPY:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyKRW:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyKWD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyLKR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyMMK:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyMXN:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyMYR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyNGN:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyNOK:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyNZD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyPHP:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyPKR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyPLN:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyRUB:
		return true
	case GetWhitelistedTokensPricesParamsCurrencySAR:
		return true
	case GetWhitelistedTokensPricesParamsCurrencySEK:
		return true
	case GetWhitelistedTokensPricesParamsCurrencySGD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyTHB:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyTRY:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyTWD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyUAH:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyUSD:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyVEF:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyVND:
		return true
	case GetWhitelistedTokensPricesParamsCurrencyZAR:
		return true
	default:
		return false
	}
}

// Defines values for GetPricesForRequestedTokensParamsCurrency.
const (
	GetPricesForRequestedTokensParamsCurrencyAED GetPricesForRequestedTokensParamsCurrency = "AED"
	GetPricesForRequestedTokensParamsCurrencyARS GetPricesForRequestedTokensParamsCurrency = "ARS"
	GetPricesForRequestedTokensParamsCurrencyAUD GetPricesForRequestedTokensParamsCurrency = "AUD"
	GetPricesForRequestedTokensParamsCurrencyBDT GetPricesForRequestedTokensParamsCurrency = "BDT"
	GetPricesForRequestedTokensParamsCurrencyBHD GetPricesForRequestedTokensParamsCurrency = "BHD"
	GetPricesForRequestedTokensParamsCurrencyBMD GetPricesForRequestedTokensParamsCurrency = "BMD"
	GetPricesForRequestedTokensParamsCurrencyBRL GetPricesForRequestedTokensParamsCurrency = "BRL"
	GetPricesForRequestedTokensParamsCurrencyCAD GetPricesForRequestedTokensParamsCurrency = "CAD"
	GetPricesForRequestedTokensParamsCurrencyCHF GetPricesForRequestedTokensParamsCurrency = "CHF"
	GetPricesForRequestedTokensParamsCurrencyCLP GetPricesForRequestedTokensParamsCurrency = "CLP"
	GetPricesForRequestedTokensParamsCurrencyCNY GetPricesForRequestedTokensParamsCurrency = "CNY"
	GetPricesForRequestedTokensParamsCurrencyCZK GetPricesForRequestedTokensParamsCurrency = "CZK"
	GetPricesForRequestedTokensParamsCurrencyDKK GetPricesForRequestedTokensParamsCurrency = "DKK"
	GetPricesForRequestedTokensParamsCurrencyEUR GetPricesForRequestedTokensParamsCurrency = "EUR"
	GetPricesForRequestedTokensParamsCurrencyGBP GetPricesForRequestedTokensParamsCurrency = "GBP"
	GetPricesForRequestedTokensParamsCurrencyHKD GetPricesForRequestedTokensParamsCurrency = "HKD"
	GetPricesForRequestedTokensParamsCurrencyHUF GetPricesForRequestedTokensParamsCurrency = "HUF"
	GetPricesForRequestedTokensParamsCurrencyIDR GetPricesForRequestedTokensParamsCurrency = "IDR"
	GetPricesForRequestedTokensParamsCurrencyILS GetPricesForRequestedTokensParamsCurrency = "ILS"
	GetPricesForRequestedTokensParamsCurrencyINR GetPricesForRequestedTokensParamsCurrency = "INR"
	GetPricesForRequestedTokensParamsCurrencyJPY GetPricesForRequestedTokensParamsCurrency = "JPY"
	GetPricesForRequestedTokensParamsCurrencyKRW GetPricesForRequestedTokensParamsCurrency = "KRW"
	GetPricesForRequestedTokensParamsCurrencyKWD GetPricesForRequestedTokensParamsCurrency = "KWD"
	GetPricesForRequestedTokensParamsCurrencyLKR GetPricesForRequestedTokensParamsCurrency = "LKR"
	GetPricesForRequestedTokensParamsCurrencyMMK GetPricesForRequestedTokensParamsCurrency = "MMK"
	GetPricesForRequestedTokensParamsCurrencyMXN GetPricesForRequestedTokensParamsCurrency = "MXN"
	GetPricesForRequestedTokensParamsCurrencyMYR GetPricesForRequestedTokensParamsCurrency = "MYR"
	GetPricesForRequestedTokensParamsCurrencyNGN GetPricesForRequestedTokensParamsCurrency = "NGN"
	GetPricesForRequestedTokensParamsCurrencyNOK GetPricesForRequestedTokensParamsCurrency = "NOK"
	GetPricesForRequestedTokensParamsCurrencyNZD GetPricesForRequestedTokensParamsCurrency = "NZD"
	GetPricesForRequestedTokensParamsCurrencyPHP GetPricesForRequestedTokensParamsCurrency = "PHP"
	GetPricesForRequestedTokensParamsCurrencyPKR GetPricesForRequestedTokensParamsCurrency = "PKR"
	GetPricesForRequestedTokensParamsCurrencyPLN GetPricesForRequestedTokensParamsCurrency = "PLN"
	GetPricesForRequestedTokensParamsCurrencyRUB GetPricesForRequestedTokensParamsCurrency = "RUB"
	GetPricesForRequestedTokensParamsCurrencySAR GetPricesForRequestedTokensParamsCurrency = "SAR"
	GetPricesForRequestedTokensParamsCurrencySEK GetPricesForRequestedTokensParamsCurrency = "SEK"
	GetPricesForRequestedTokensParamsCurrencySGD GetPricesForRequestedTokensParamsCurrency = "SGD"
	GetPricesForRequestedTokensParamsCurrencyTHB GetPricesForRequestedTokensParamsCurrency = "THB"
	GetPricesForRequestedTokensParamsCurrencyTRY GetPricesForRequestedTokensParamsCurrency = "TRY"
	GetPricesForRequestedTokensParamsCurrencyTWD GetPricesForRequestedTokensParamsCurrency = "TWD"
	GetPricesForRequestedTokensParamsCurrencyUAH GetPricesForRequestedTokensParamsCurrency = "UAH"
	GetPricesForRequestedTokensParamsCurrencyUSD GetPricesForRequestedTokensParamsCurrency = "USD"
	GetPricesForRequestedTokensParamsCurrencyVEF GetPricesForRequestedTokensParamsCurrency = "VEF"
	GetPricesForRequestedTokensParamsCurrencyVND GetPricesForRequestedTokensParamsCurrency = "VND"
	GetPricesForRequestedTokensParamsCurrencyZAR GetPricesForRequestedTokensParamsCurrency = "ZAR"
)

// Valid indicates whether the value is a known member of the GetPricesForRequestedTokensParamsCurrency enum.
func (e GetPricesForRequestedTokensParamsCurrency) Valid() bool {
	switch e {
	case GetPricesForRequestedTokensParamsCurrencyAED:
		return true
	case GetPricesForRequestedTokensParamsCurrencyARS:
		return true
	case GetPricesForRequestedTokensParamsCurrencyAUD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyBDT:
		return true
	case GetPricesForRequestedTokensParamsCurrencyBHD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyBMD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyBRL:
		return true
	case GetPricesForRequestedTokensParamsCurrencyCAD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyCHF:
		return true
	case GetPricesForRequestedTokensParamsCurrencyCLP:
		return true
	case GetPricesForRequestedTokensParamsCurrencyCNY:
		return true
	case GetPricesForRequestedTokensParamsCurrencyCZK:
		return true
	case GetPricesForRequestedTokensParamsCurrencyDKK:
		return true
	case GetPricesForRequestedTokensParamsCurrencyEUR:
		return true
	case GetPricesForRequestedTokensParamsCurrencyGBP:
		return true
	case GetPricesForRequestedTokensParamsCurrencyHKD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyHUF:
		return true
	case GetPricesForRequestedTokensParamsCurrencyIDR:
		return true
	case GetPricesForRequestedTokensParamsCurrencyILS:
		return true
	case GetPricesForRequestedTokensParamsCurrencyINR:
		return true
	case GetPricesForRequestedTokensParamsCurrencyJPY:
		return true
	case GetPricesForRequestedTokensParamsCurrencyKRW:
		return true
	case GetPricesForRequestedTokensParamsCurrencyKWD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyLKR:
		return true
	case GetPricesForRequestedTokensParamsCurrencyMMK:
		return true
	case GetPricesForRequestedTokensParamsCurrencyMXN:
		return true
	case GetPricesForRequestedTokensParamsCurrencyMYR:
		return true
	case GetPricesForRequestedTokensParamsCurrencyNGN:
		return true
	case GetPricesForRequestedTokensParamsCurrencyNOK:
		return true
	case GetPricesForRequestedTokensParamsCurrencyNZD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyPHP:
		return true
	case GetPricesForRequestedTokensParamsCurrencyPKR:
		return true
	case GetPricesForRequestedTokensParamsCurrencyPLN:
		return true
	case GetPricesForRequestedTokensParamsCurrencyRUB:
		return true
	case GetPricesForRequestedTokensParamsCurrencySAR:
		return true
	case GetPricesForRequestedTokensParamsCurrencySEK:
		return true
	case GetPricesForRequestedTokensParamsCurrencySGD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyTHB:
		return true
	case GetPricesForRequestedTokensParamsCurrencyTRY:
		return true
	case GetPricesForRequestedTokensParamsCurrencyTWD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyUAH:
		return true
	case GetPricesForRequestedTokensParamsCurrencyUSD:
		return true
	case GetPricesForRequestedTokensParamsCurrencyVEF:
		return true
	case GetPricesForRequestedTokensParamsCurrencyVND:
		return true
	case GetPricesForRequestedTokensParamsCurrencyZAR:
		return true
	default:
		return false
	}
}

// CurrenciesResponseDto defines model for CurrenciesResponseDto.
type CurrenciesResponseDto struct {
	Codes []string `json:"codes"`
}

// GetPricesRequestDto defines model for GetPricesRequestDto.
type GetPricesRequestDto struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency GetPricesRequestDtoCurrency `json:"currency,omitempty"`

	// Tokens Example: ["0x111111111117dc0aa78b770fa6a738034120c302"]
	Tokens []string `json:"tokens"`
}

// GetPricesRequestDtoCurrency If no currency provided, then price returned in native Wei
type GetPricesRequestDtoCurrency string

// GetWhitelistedTokensPricesParams defines parameters for GetWhitelistedTokensPrices.
type GetWhitelistedTokensPricesParams struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency GetWhitelistedTokensPricesParamsCurrency `url:"currency,omitempty" json:"currency,omitempty"`
}

// GetWhitelistedTokensPricesParamsCurrency defines parameters for GetWhitelistedTokensPrices.
type GetWhitelistedTokensPricesParamsCurrency string

// GetPricesForRequestedTokensParams defines parameters for GetPricesForRequestedTokens.
type GetPricesForRequestedTokensParams struct {
	// Currency If no currency provided, then price returned in native Wei
	Currency GetPricesForRequestedTokensParamsCurrency `url:"currency,omitempty" json:"currency,omitempty"`
}

// GetPricesForRequestedTokensParamsCurrency defines parameters for GetPricesForRequestedTokens.
type GetPricesForRequestedTokensParamsCurrency string

// GetPricesForRequestedTokensJSONRequestBody defines body for GetPricesForRequestedTokens for application/json ContentType.
type GetPricesForRequestedTokensJSONRequestBody = GetPricesRequestDto
