// Package orderbook provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package orderbook

// Defines values for GetLimitOrderParamsSortBy.
const (
	GetLimitOrderParamsSortByCreateDateTime GetLimitOrderParamsSortBy = "createDateTime"
	GetLimitOrderParamsSortByMakerAmount    GetLimitOrderParamsSortBy = "makerAmount"
	GetLimitOrderParamsSortByMakerRate      GetLimitOrderParamsSortBy = "makerRate"
	GetLimitOrderParamsSortByTakerAmount    GetLimitOrderParamsSortBy = "takerAmount"
	GetLimitOrderParamsSortByTakerRate      GetLimitOrderParamsSortBy = "takerRate"
)

// Valid indicates whether the value is a known member of the GetLimitOrderParamsSortBy enum.
func (e GetLimitOrderParamsSortBy) Valid() bool {
	switch e {
	case GetLimitOrderParamsSortByCreateDateTime:
		return true
	case GetLimitOrderParamsSortByMakerAmount:
		return true
	case GetLimitOrderParamsSortByMakerRate:
		return true
	case GetLimitOrderParamsSortByTakerAmount:
		return true
	case GetLimitOrderParamsSortByTakerRate:
		return true
	default:
		return false
	}
}

// Defines values for LimitOrdersQueryParamsSortBy.
const (
	LimitOrdersQueryParamsSortByCreateDateTime LimitOrdersQueryParamsSortBy = "createDateTime"
	LimitOrdersQueryParamsSortByMakerAmount    LimitOrdersQueryParamsSortBy = "makerAmount"
	LimitOrdersQueryParamsSortByMakerRate      LimitOrdersQueryParamsSortBy = "makerRate"
	LimitOrdersQueryParamsSortByTakerAmount    LimitOrdersQueryParamsSortBy = "takerAmount"
	LimitOrdersQueryParamsSortByTakerRate      LimitOrdersQueryParamsSortBy = "takerRate"
)

// Valid indicates whether the value is a known member of the LimitOrdersQueryParamsSortBy enum.
func (e LimitOrdersQueryParamsSortBy) Valid() bool {
	switch e {
	case LimitOrdersQueryParamsSortByCreateDateTime:
		return true
	case LimitOrdersQueryParamsSortByMakerAmount:
		return true
	case LimitOrdersQueryParamsSortByMakerRate:
		return true
	case LimitOrdersQueryParamsSortByTakerAmount:
		return true
	case LimitOrdersQueryParamsSortByTakerRate:
		return true
	default:
		return false
	}
}

// LimitOrderV3Data defines model for LimitOrderV3Data.
type LimitOrderV3Data struct {
	// AllowedSender An address of the wallet or contract who will be able to fill this order (equals to Zero address on public orders)
	AllowedSender string `json:"allowedSender,omitempty"`

	// Interactions Merged offsets of each field in interactions
	Interactions string `json:"interactions,omitempty"`

	// Maker An address of the maker (wallet or contract address)
	Maker string `json:"maker"`

	// MakerAsset Address of the maker asset
	MakerAsset string `json:"makerAsset"`

	// MakingAmount Order maker's token amount
	MakingAmount string `json:"makingAmount"`

	// Offsets An interaction call data. ABI encoded set of makerAssetData, takerAssetData, getMakingAmount, getTakingAmount, predicate, permit, preInteraction, postInteraction
	Offsets string `json:"offsets,omitempty"`

	// Receiver An address of the wallet or contract who will receive filled amount (equals to Zero address for receiver == makerAddress)
	Receiver string `json:"receiver,omitempty"`

	// Salt Some unique value. It is necessary to be able to create limit orders with the same parameters (so that they have a different hash)
	Salt string `json:"salt"`

	// TakerAsset Address of the taker asset
	TakerAsset string `json:"takerAsset"`

	// TakingAmount Order taker's token amount
	TakingAmount string `json:"takingAmount"`
}

// LimitOrderV3Request defines model for LimitOrderV3Request.
type LimitOrderV3Request struct {
	Data LimitOrderV3Data `json:"data"`

	// OrderHash Hash of the limit order typed data
	OrderHash string `json:"orderHash"`

	// Signature Signature of the limit order typed data (using signTypedData_v4)
	Signature string `json:"signature"`
}

// GetLimitOrderParams defines parameters for GetLimitOrder.
type GetLimitOrderParams struct {
	// Page Pagination step, default: 1 (page = offset / limit)
	Page float32 `url:"page,omitempty" json:"page,omitempty"`

	// Limit Number of limit orders to receive (default: 100, max: 500)
	Limit float32 `url:"limit,omitempty" json:"limit,omitempty"`

	// Statuses JSON an array of statuses by which limit orders will be filtered: 1 - valid limit orders, 2 - temporary invalid limit orders, 3 - invalid limit orders
	Statuses []float32                 `url:"statuses,omitempty" json:"statuses,omitempty"`
	SortBy   GetLimitOrderParamsSortBy `url:"sortBy,omitempty" json:"sortBy,omitempty"`

	// TakerAsset Address of the taker asset
	TakerAsset string `url:"takerAsset,omitempty" json:"takerAsset,omitempty"`

	// MakerAsset Address of the maker asset
	MakerAsset string `url:"makerAsset,omitempty" json:"makerAsset,omitempty"`
}

// GetLimitOrderParamsSortBy defines parameters for GetLimitOrder.
type GetLimitOrderParamsSortBy string

// LimitOrdersQueryParams defines parameters for LimitOrdersQuery.
type LimitOrdersQueryParams struct {
	// Page Pagination step, default: 1 (page = offset / limit)
	Page float32 `url:"page,omitempty" json:"page,omitempty"`

	// Limit Number of limit orders to receive (default: 100, max: 500)
	Limit float32 `url:"limit,omitempty" json:"limit,omitempty"`

	// Statuses JSON an array of statuses by which limit orders will be filtered: 1 - valid limit orders, 2 - temporary invalid limit orders, 3 - invalid limit orders
	Statuses []float32                    `url:"statuses,omitempty" json:"statuses,omitempty"`
	SortBy   LimitOrdersQueryParamsSortBy `url:"sortBy,omitempty" json:"sortBy,omitempty"`

	// TakerAsset Address of the maker asset
	TakerAsset string `url:"takerAsset,omitempty" json:"takerAsset,omitempty"`

	// MakerAsset Address of the maker asset
	MakerAsset string `url:"makerAsset,omitempty" json:"makerAsset,omitempty"`
}

// LimitOrdersQueryParamsSortBy defines parameters for LimitOrdersQuery.
type LimitOrdersQueryParamsSortBy string

// OrdersCountQueryParams defines parameters for OrdersCountQuery.
type OrdersCountQueryParams struct {
	Statuses []string `url:"statuses" json:"statuses"`
}

// EventsQueryParams defines parameters for EventsQuery.
type EventsQueryParams struct {
	Limit float32 `url:"limit" json:"limit"`
}

// CreateLimitOrderJSONRequestBody defines body for CreateLimitOrder for application/json ContentType.
type CreateLimitOrderJSONRequestBody = LimitOrderV3Request
