// Package traces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package traces

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CoreBuiltinBlockTracesDtoType.
const (
	CoreBuiltinBlockTracesDtoTypeBUILTIN             CoreBuiltinBlockTracesDtoType = "BUILTIN"
	CoreBuiltinBlockTracesDtoTypeCUSTOM              CoreBuiltinBlockTracesDtoType = "CUSTOM"
	CoreBuiltinBlockTracesDtoTypeCUSTOMGO            CoreBuiltinBlockTracesDtoType = "CUSTOM_GO"
	CoreBuiltinBlockTracesDtoTypeCUSTOMWITHOUTSTORE  CoreBuiltinBlockTracesDtoType = "CUSTOM_WITHOUT_STORE"
	CoreBuiltinBlockTracesDtoTypeOLDARBITRUMRAWTRACE CoreBuiltinBlockTracesDtoType = "OLD_ARBITRUM_RAW_TRACE"
)

// Valid indicates whether the value is a known member of the CoreBuiltinBlockTracesDtoType enum.
func (e CoreBuiltinBlockTracesDtoType) Valid() bool {
	switch e {
	case CoreBuiltinBlockTracesDtoTypeBUILTIN:
		return true
	case CoreBuiltinBlockTracesDtoTypeCUSTOM:
		return true
	case CoreBuiltinBlockTracesDtoTypeCUSTOMGO:
		return true
	case CoreBuiltinBlockTracesDtoTypeCUSTOMWITHOUTSTORE:
		return true
	case CoreBuiltinBlockTracesDtoTypeOLDARBITRUMRAWTRACE:
		return true
	default:
		return false
	}
}

// Defines values for CoreBuiltinCallTraceDtoType.
const (
	CoreBuiltinCallTraceDtoTypeCALL          CoreBuiltinCallTraceDtoType = "CALL"
	CoreBuiltinCallTraceDtoTypeCALLCODE      CoreBuiltinCallTraceDtoType = "CALLCODE"
	CoreBuiltinCallTraceDtoTypeCREATE        CoreBuiltinCallTraceDtoType = "CREATE"
	CoreBuiltinCallTraceDtoTypeCREATE2       CoreBuiltinCallTraceDtoType = "CREATE2"
	CoreBuiltinCallTraceDtoTypeDELEGATECALL  CoreBuiltinCallTraceDtoType = "DELEGATECALL"
	CoreBuiltinCallTraceDtoTypeINVALID       CoreBuiltinCallTraceDtoType = "INVALID"
	CoreBuiltinCallTraceDtoTypeSELFDESTRUCT  CoreBuiltinCallTraceDtoType = "SELFDESTRUCT"
	CoreBuiltinCallTraceDtoTypeSTATICCALL    CoreBuiltinCallTraceDtoType = "STATICCALL"
	CoreBuiltinCallTraceDtoTypeSTOP          CoreBuiltinCallTraceDtoType = "STOP"
	CoreBuiltinCallTraceDtoTypeTRANSFERETHER CoreBuiltinCallTraceDtoType = "TRANSFER_ETHER"
)

// Valid indicates whether the value is a known member of the CoreBuiltinCallTraceDtoType enum.
func (e CoreBuiltinCallTraceDtoType) Valid() bool {
	switch e {
	case CoreBuiltinCallTraceDtoTypeCALL:
		return true
	case CoreBuiltinCallTraceDtoTypeCALLCODE:
		return true
	case CoreBuiltinCallTraceDtoTypeCREATE:
		return true
	case CoreBuiltinCallTraceDtoTypeCREATE2:
		return true
	case CoreBuiltinCallTraceDtoTypeDELEGATECALL:
		return true
	case CoreBuiltinCallTraceDtoTypeINVALID:
		return true
	case CoreBuiltinCallTraceDtoTypeSELFDESTRUCT:
		return true
	case CoreBuiltinCallTraceDtoTypeSTATICCALL:
		return true
	case CoreBuiltinCallTraceDtoTypeSTOP:
		return true
	case CoreBuiltinCallTraceDtoTypeTRANSFERETHER:
		return true
	default:
		return false
	}
}

// Defines values for CoreBuiltinTransactionRootSuccessTraceDtoType.
const (
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCALL          CoreBuiltinTransactionRootSuccessTraceDtoType = "CALL"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCALLCODE      CoreBuiltinTransactionRootSuccessTraceDtoType = "CALLCODE"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCREATE        CoreBuiltinTransactionRootSuccessTraceDtoType = "CREATE"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCREATE2       CoreBuiltinTransactionRootSuccessTraceDtoType = "CREATE2"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeDELEGATECALL  CoreBuiltinTransactionRootSuccessTraceDtoType = "DELEGATECALL"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeINVALID       CoreBuiltinTransactionRootSuccessTraceDtoType = "INVALID"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeSELFDESTRUCT  CoreBuiltinTransactionRootSuccessTraceDtoType = "SELFDESTRUCT"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeSTATICCALL    CoreBuiltinTransactionRootSuccessTraceDtoType = "STATICCALL"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeSTOP          CoreBuiltinTransactionRootSuccessTraceDtoType = "STOP"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeTRANSFERETHER CoreBuiltinTransactionRootSuccessTraceDtoType = "TRANSFER_ETHER"
)

// Valid indicates whether the value is a known member of the CoreBuiltinTransactionRootSuccessTraceDtoType enum.
func (e CoreBuiltinTransactionRootSuccessTraceDtoType) Valid() bool {
	switch e {
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeCALL:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeCALLCODE:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeCREATE:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeCREATE2:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeDELEGATECALL:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeINVALID:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeSELFDESTRUCT:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeSTATICCALL:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeSTOP:
		return true
	case CoreBuiltinTransactionRootSuccessTraceDtoTypeTRANSFERETHER:
		return true
	default:
		return false
	}
}

// Defines values for CoreCustomBlockTraceDtoType.
const (
	CoreCustomBlockTraceDtoTypeBUILTIN             CoreCustomBlockTraceDtoType = "BUILTIN"
	CoreCustomBlockTraceDtoTypeCUSTOM              CoreCustomBlockTraceDtoType = "CUSTOM"
	CoreCustomBlockTraceDtoTypeCUSTOMGO            CoreCustomBlockTraceDtoType = "CUSTOM_GO"
	CoreCustomBlockTraceDtoTypeCUSTOMWITHOUTSTORE  CoreCustomBlockTraceDtoType = "CUSTOM_WITHOUT_STORE"
	CoreCustomBlockTraceDtoTypeOLDARBITRUMRAWTRACE CoreCustomBlockTraceDtoType = "OLD_ARBITRUM_RAW_TRACE"
)

// Valid indicates whether the value is a known member of the CoreCustomBlockTraceDtoType enum.
func (e CoreCustomBlockTraceDtoType) Valid() bool {
	switch e {
	case CoreCustomBlockTraceDtoTypeBUILTIN:
		return true
	case CoreCustomBlockTraceDtoTypeCUSTOM:
		return true
	case CoreCustomBlockTraceDtoTypeCUSTOMGO:
		return true
	case CoreCustomBlockTraceDtoTypeCUSTOMWITHOUTSTORE:
		return true
	case CoreCustomBlockTraceDtoTypeOLDARBITRUMRAWTRACE:
		return true
	default:
		return false
	}
}

// Defines values for CoreCustomRootTxEventCallstackTraceFullDtoStatus.
const (
	CoreCustomRootTxEventCallstackTraceFullDtoStatusERROR          CoreCustomRootTxEventCallstackTraceFullDtoStatus = "ERROR"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusERRORUNWIND    CoreCustomRootTxEventCallstackTraceFullDtoStatus = "ERROR_UNWIND"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusINVALIDOPCODE  CoreCustomRootTxEventCallstackTraceFullDtoStatus = "INVALID_OPCODE"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusNOCONTRACT     CoreCustomRootTxEventCallstackTraceFullDtoStatus = "NO_CONTRACT"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusOUTOFGAS       CoreCustomRootTxEventCallstackTraceFullDtoStatus = "OUT_OF_GAS"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusRETURNED       CoreCustomRootTxEventCallstackTraceFullDtoStatus = "RETURNED"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusREVERTED       CoreCustomRootTxEventCallstackTraceFullDtoStatus = "REVERTED"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusSELFDESTRUCTED CoreCustomRootTxEventCallstackTraceFullDtoStatus = "SELFDESTRUCTED"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusSTOPPED        CoreCustomRootTxEventCallstackTraceFullDtoStatus = "STOPPED"
)

// Valid indicates whether the value is a known member of the CoreCustomRootTxEventCallstackTraceFullDtoStatus enum.
func (e CoreCustomRootTxEventCallstackTraceFullDtoStatus) Valid() bool {
	switch e {
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusERROR:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusERRORUNWIND:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusINVALIDOPCODE:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusNOCONTRACT:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusOUTOFGAS:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusRETURNED:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusREVERTED:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusSELFDESTRUCTED:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoStatusSTOPPED:
		return true
	default:
		return false
	}
}

// Defines values for CoreCustomRootTxEventCallstackTraceFullDtoType.
const (
	CoreCustomRootTxEventCallstackTraceFullDtoTypeCALL          CoreCustomRootTxEventCallstackTraceFullDtoType = "CALL"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeCALLCODE      CoreCustomRootTxEventCallstackTraceFullDtoType = "CALLCODE"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeCREATE        CoreCustomRootTxEventCallstackTraceFullDtoType = "CREATE"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeCREATE2       CoreCustomRootTxEventCallstackTraceFullDtoType = "CREATE2"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeDELEGATECALL  CoreCustomRootTxEventCallstackTraceFullDtoType = "DELEGATECALL"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeINVALID       CoreCustomRootTxEventCallstackTraceFullDtoType = "INVALID"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeSELFDESTRUCT  CoreCustomRootTxEventCallstackTraceFullDtoType = "SELFDESTRUCT"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeSTATICCALL    CoreCustomRootTxEventCallstackTraceFullDtoType = "STATICCALL"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeSTOP          CoreCustomRootTxEventCallstackTraceFullDtoType = "STOP"
	CoreCustomRootTxEventCallstackTraceFullDtoTypeTRANSFERETHER CoreCustomRootTxEventCallstackTraceFullDtoType = "TRANSFER_ETHER"
)

// Valid indicates whether the value is a known member of the CoreCustomRootTxEventCallstackTraceFullDtoType enum.
func (e CoreCustomRootTxEventCallstackTraceFullDtoType) Valid() bool {
	switch e {
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeCALL:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeCALLCODE:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeCREATE:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeCREATE2:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeDELEGATECALL:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeINVALID:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeSELFDESTRUCT:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeSTATICCALL:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeSTOP:
		return true
	case CoreCustomRootTxEventCallstackTraceFullDtoTypeTRANSFERETHER:
		return true
	default:
		return false
	}
}

// Defines values for CoreCustomTxEventCallstackTraceDtoStatus.
const (
	CoreCustomTxEventCallstackTraceDtoStatusERROR          CoreCustomTxEventCallstackTraceDtoStatus = "ERROR"
	CoreCustomTxEventCallstackTraceDtoStatusERRORUNWIND    CoreCustomTxEventCallstackTraceDtoStatus = "ERROR_UNWIND"
	CoreCustomTxEventCallstackTraceDtoStatusINVALIDOPCODE  CoreCustomTxEventCallstackTraceDtoStatus = "INVALID_OPCODE"
	CoreCustomTxEventCallstackTraceDtoStatusNOCONTRACT     CoreCustomTxEventCallstackTraceDtoStatus = "NO_CONTRACT"
	CoreCustomTxEventCallstackTraceDtoStatusOUTOFGAS       CoreCustomTxEventCallstackTraceDtoStatus = "OUT_OF_GAS"
	CoreCustomTxEventCallstackTraceDtoStatusRETURNED       CoreCustomTxEventCallstackTraceDtoStatus = "RETURNED"
	CoreCustomTxEventCallstackTraceDtoStatusREVERTED       CoreCustomTxEventCallstackTraceDtoStatus = "REVERTED"
	CoreCustomTxEventCallstackTraceDtoStatusSELFDESTRUCTED CoreCustomTxEventCallstackTraceDtoStatus = "SELFDESTRUCTED"
	CoreCustomTxEventCallstackTraceDtoStatusSTOPPED        CoreCustomTxEventCallstackTraceDtoStatus = "STOPPED"
)

// Valid indicates whether the value is a known member of the CoreCustomTxEventCallstackTraceDtoStatus enum.
func (e CoreCustomTxEventCallstackTraceDtoStatus) Valid() bool {
	switch e {
	case CoreCustomTxEventCallstackTraceDtoStatusERROR:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusERRORUNWIND:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusINVALIDOPCODE:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusNOCONTRACT:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusOUTOFGAS:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusRETURNED:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusREVERTED:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusSELFDESTRUCTED:
		return true
	case CoreCustomTxEventCallstackTraceDtoStatusSTOPPED:
		return true
	default:
		return false
	}
}

// Defines values for PlainTransactionTraceWithTypeDtoType.
const (
	PlainTransactionTraceWithTypeDtoTypeBUILTIN             PlainTransactionTraceWithTypeDtoType = "BUILTIN"
	PlainTransactionTraceWithTypeDtoTypeCUSTOM              PlainTransactionTraceWithTypeDtoType = "CUSTOM"
	PlainTransactionTraceWithTypeDtoTypeCUSTOMGO            PlainTransactionTraceWithTypeDtoType = "CUSTOM_GO"
	PlainTransactionTraceWithTypeDtoTypeCUSTOMWITHOUTSTORE  PlainTransactionTraceWithTypeDtoType = "CUSTOM_WITHOUT_STORE"
	PlainTransactionTraceWithTypeDtoTypeOLDARBITRUMRAWTRACE PlainTransactionTraceWithTypeDtoType = "OLD_ARBITRUM_RAW_TRACE"
)

// Valid indicates whether the value is a known member of the PlainTransactionTraceWithTypeDtoType enum.
func (e PlainTransactionTraceWithTypeDtoType) Valid() bool {
	switch e {
	case PlainTransactionTraceWithTypeDtoTypeBUILTIN:
		return true
	case PlainTransactionTraceWithTypeDtoTypeCUSTOM:
		return true
	case PlainTransactionTraceWithTypeDtoTypeCUSTOMGO:
		return true
	case PlainTransactionTraceWithTypeDtoTypeCUSTOMWITHOUTSTORE:
		return true
	case PlainTransactionTraceWithTypeDtoTypeOLDARBITRUMRAWTRACE:
		return true
	default:
		return false
	}
}

// CoreBuiltinBlockTracesDto defines model for CoreBuiltinBlockTracesDto.
type CoreBuiltinBlockTracesDto struct {
	// BlockHash Example: 0xb80490b1bed7a31536b888de977f92b5c03707bf8c69ab3d066a2eef3dc2e26c
	BlockHash string `json:"blockHash"`

	// BlockNumber Example: 16123123
	BlockNumber float32 `json:"blockNumber,omitempty"`

	// BlockTimestamp Example: 0x64bf5cde
	BlockTimestamp string                                      `json:"blockTimestamp"`
	Traces         []CoreBuiltinTransactionRootSuccessTraceDto `json:"traces"`

	// Type Example: BUILTIN
	Type CoreBuiltinBlockTracesDtoType `json:"type"`

	// Version Example: v1.2.3
	Version string `json:"version"`
}

// CoreBuiltinBlockTracesDtoType Example: BUILTIN
type CoreBuiltinBlockTracesDtoType string

// CoreBuiltinCallTraceDto defines model for CoreBuiltinCallTraceDto.
type CoreBuiltinCallTraceDto struct {
	Calls []CoreBuiltinCallTraceDto `json:"calls"`

	// Error Example: error
	Error string `json:"error"`

	// From Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	From string `json:"from"`

	// Gas Example: 0x3e48f
	Gas string `json:"gas"`

	// GasUsed Example: 0x5da9
	GasUsed float32 `json:"gasUsed"`

	// Input Example: 0xd0e30db0
	Input string `json:"input"`

	// IsParentHasError Example: true
	IsParentHasError bool `json:"isParentHasError"`

	// Output Example: 0x0000000000000000000000000000000000000000000000000000000000000001
	Output string `json:"output"`

	// To Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	To string `json:"to"`

	// Type Example: CALL
	Type CoreBuiltinCallTraceDtoType `json:"type"`

	// Value Example: 0x5f68e8131ecf80000
	Value string `json:"value"`
}

// CoreBuiltinCallTraceDtoType Example: CALL
type CoreBuiltinCallTraceDtoType string

// CoreBuiltinTraceLogDto defines model for CoreBuiltinTraceLogDto.
type CoreBuiltinTraceLogDto struct {
	// Contract Example: 0x0000000000000000000000000000000000001010
	Contract string `json:"contract"`

	// Data Example: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	Data string `json:"data"`

	// Topics Example: ["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925","0x00000000000000000000000059eb67ecbb7e68ee94114b2f77d91074404504be","0x000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff"]
	Topics [][]interface{} `json:"topics"`
}

// CoreBuiltinTransactionRootSuccessTraceDto defines model for CoreBuiltinTransactionRootSuccessTraceDto.
type CoreBuiltinTransactionRootSuccessTraceDto struct {
	Calls []CoreBuiltinCallTraceDto `json:"calls"`

	// Error Example: error
	Error  string                   `json:"error"`
	Events []CoreBuiltinTraceLogDto `json:"events"`

	// From Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	From string `json:"from"`

	// Gas Example: 0x3e48f
	Gas string `json:"gas"`

	// GasHex Example: 0x35b60
	GasHex string `json:"gasHex"`

	// GasPrice Example: 0x123
	GasPrice string `json:"gasPrice"`

	// GasUsed Example: 0x5da9
	GasUsed float32 `json:"gasUsed"`

	// Input Example: 0xd0e30db0
	Input string `json:"input"`

	// MaxFeePerGas Example: 0x345
	MaxFeePerGas string `json:"maxFeePerGas"`

	// MaxPriorityFeePerGas Example: 0x123
	MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`

	// Nonce Example: 0x1
	Nonce string `json:"nonce"`

	// Output Example: 0x0000000000000000000000000000000000000000000000000000000000000001
	Output string `json:"output"`

	// RevertReason Example: error
	RevertReason string `json:"revertReason"`

	// To Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	To string `json:"to"`

	// TxHash Example: 0xbf424a717932e4868644f69e8f297ce51d5f4596089635312b2ad9c610cc0018
	TxHash string `json:"txHash"`

	// Type Example: CALL
	Type CoreBuiltinTransactionRootSuccessTraceDtoType `json:"type"`

	// Value Example: 0x5f68e8131ecf80000
	Value string `json:"value"`
}

// CoreBuiltinTransactionRootSuccessTraceDtoType Example: CALL
type CoreBuiltinTransactionRootSuccessTraceDtoType string

// CoreCustomBlockTraceDto defines model for CoreCustomBlockTraceDto.
type CoreCustomBlockTraceDto struct {
	// BlockHash Example: 0xb80490b1bed7a31536b888de977f92b5c03707bf8c69ab3d066a2eef3dc2e26c
	BlockHash string `json:"blockHash"`

	// BlockTimestamp Example: 0x64bf5cde
	BlockTimestamp string `json:"blockTimestamp"`

	// Number Example: 17123123
	Number float32                               `json:"number"`
	Traces []CoreCustomBlockTraceDto_Traces_Item `json:"traces"`

	// Type Example: CUSTOM
	Type CoreCustomBlockTraceDtoType `json:"type"`

	// Version Example: v1.2.3
	Version string `json:"version"`
}

// CoreCustomBlockTraceDto_Traces_Item defines model for CoreCustomBlockTraceDto.traces.Item.
type CoreCustomBlockTraceDto_Traces_Item struct {
	union json.RawMessage
}

// CoreCustomBlockTraceDtoType Example: CUSTOM
type CoreCustomBlockTraceDtoType string

// CoreCustomErrorTransactionTraceDto defines model for CoreCustomErrorTransactionTraceDto.
type CoreCustomErrorTransactionTraceDto struct {
	// Error Example: error
	Error string `json:"error"`

	// GasHex Example: 0x3e48f
	GasHex string `json:"gasHex"`

	// GasPrice Example: 0x3e48f
	GasPrice string `json:"gasPrice"`

	// MaxFeePerGas Example: 0x3e48f
	MaxFeePerGas string `json:"maxFeePerGas"`

	// MaxPriorityFeePerGas Example: 0x3e48f
	MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`

	// Nonce Example: 0x1
	Nonce string `json:"nonce"`

	// TxHash Example: 0xbf424a717932e4868644f69e8f297ce51d5f4596089635312b2ad9c610cc0018
	TxHash string `json:"txHash"`
}

// CoreCustomRootTxEventCallstackTraceFullDto defines model for CoreCustomRootTxEventCallstackTraceFullDto.
type CoreCustomRootTxEventCallstackTraceFullDto struct {
	// Address Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	Address string                               `json:"address"`
	Calls   []CoreCustomTxEventCallstackTraceDto `json:"calls"`

	// Depth Example: 3
	Depth float32 `json:"depth"`

	// DestructAddress Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	DestructAddress string `json:"destructAddress"`

	// ErrorDetails Example: error
	ErrorDetails string `json:"errorDetails"`

	// From Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	From string `json:"from"`

	// GasActual Example: 123
	GasActual float32 `json:"gasActual"`

	// GasHex Example: 0x123123123
	GasHex string `json:"gasHex"`

	// GasLimit Example: 123
	GasLimit float32 `json:"gasLimit"`

	// GasPrice Example: 0x3f5476a00
	GasPrice string `json:"gasPrice"`

	// GasRefund Example: 123
	GasRefund float32 `json:"gasRefund"`

	// GasUsed Example: 123
	GasUsed float32 `json:"gasUsed"`

	// Input Example: 0xd0e30db0
	Input string `json:"input"`

	// IntrinsicGas Example: 0x3e48f
	IntrinsicGas float32                 `json:"intrinsicGas"`
	Logs         []CoreCustomTraceLogDto `json:"logs"`

	// MaxFeePerGas Example: 0x3e48f
	MaxFeePerGas string `json:"maxFeePerGas"`

	// MaxPriorityFeePerGas Example: 0x3e48f
	MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`

	// Nonce Example: 0x1
	Nonce string `json:"nonce"`

	// Output Example: 0x0000000000000000000000000000000000000000000000000000000000000001
	Output string `json:"output"`

	// Res Example: 0x0000000000000000000000000000000000000000000000000000000000000001
	Res string `json:"res"`

	// Status Example: REVERTED
	Status  CoreCustomRootTxEventCallstackTraceFullDtoStatus `json:"status"`
	Storage []CustomStorageDto                               `json:"storage"`

	// Success Example: 1
	Success float32 `json:"success"`

	// Time Example: 781ns
	Time string `json:"time"`

	// To Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	To string `json:"to"`

	// TxHash Example: 0xbf424a717932e4868644f69e8f297ce51d5f4596089635312b2ad9c610cc0018
	TxHash string `json:"txHash"`

	// Type Example: CALL
	Type CoreCustomRootTxEventCallstackTraceFullDtoType `json:"type"`

	// Value Example: 0x5f68e8131ecf80000
	Value string `json:"value"`
}

// CoreCustomRootTxEventCallstackTraceFullDtoStatus Example: REVERTED
type CoreCustomRootTxEventCallstackTraceFullDtoStatus string

// CoreCustomRootTxEventCallstackTraceFullDtoType Example: CALL
type CoreCustomRootTxEventCallstackTraceFullDtoType string

// CoreCustomTraceLogDto defines model for CoreCustomTraceLogDto.
type CoreCustomTraceLogDto struct {
	// Contract Example: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
	Contract string `json:"contract"`

	// Data Example: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	Data   string          `json:"data"`
	Topics [][]interface{} `json:"topics"`
}

// CoreCustomTxEventCallstackTraceDto defines model for CoreCustomTxEventCallstackTraceDto.
type CoreCustomTxEventCallstackTraceDto struct {
	// Address Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	Address string                               `json:"address"`
	Calls   []CoreCustomTxEventCallstackTraceDto `json:"calls"`

	// Depth Example: 1
	Depth float32 `json:"depth"`

	// DestructAddress Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	DestructAddress string `json:"destructAddress"`

	// ErrorDetails Example: error
	ErrorDetails string `json:"errorDetails"`

	// From Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	From string `json:"from"`

	// Gas Example: 0x3e48f
	Gas string `json:"gas"`

	// GasCost Example: 0x3e48f
	GasCost float32 `json:"gasCost"`

	// GasLimit Example: 123
	GasLimit float32 `json:"gasLimit"`

	// GasUsed Example: 123
	GasUsed float32 `json:"gasUsed"`

	// Input Example: 0xd0e30db0
	Input string                  `json:"input"`
	Logs  []CoreCustomTraceLogDto `json:"logs"`

	// Output Example: 0x0000000000000000000000000000000000000000000000000000000000000001
	Output string `json:"output"`

	// PrevGasLimit Example: 123
	PrevGasLimit float32 `json:"prevGasLimit"`

	// Res Example: 0x0000000000000000000000000000000000000000000000000000000000000001
	Res string `json:"res"`

	// Status Example: RETURNED
	Status  CoreCustomTxEventCallstackTraceDtoStatus `json:"status"`
	Storage []CustomStorageDto                       `json:"storage"`

	// Success Example: 1
	Success float32 `json:"success"`

	// Time Example: 781ns
	Time string `json:"time"`

	// To Example: 0x71dad91e069861350c2ba882fd86762a5efe8792
	To string `json:"to"`

	// Type Example: TRANSFER_ETHER
	Type string `json:"type"`

	// Value Example: 0x5f68e8131ecf80000
	Value string `json:"value"`
}

// CoreCustomTxEventCallstackTraceDtoStatus Example: RETURNED
type CoreCustomTxEventCallstackTraceDtoStatus string

// CustomStorageDto defines model for CustomStorageDto.
type CustomStorageDto struct {
	// Key Example: 8
	Key string `json:"key"`

	// Type Example: load
	Type string `json:"type"`

	// Value Example: 63780c770000000000008255bfdbaa0269330000000000000b9057fb86bca9b0
	Value string `json:"value"`
}

// PlainTransactionTraceWithTypeDto defines model for PlainTransactionTraceWithTypeDto.
type PlainTransactionTraceWithTypeDto struct {
	TransactionTrace []PlainTransactionTraceWithTypeDto_TransactionTrace_Item `json:"transactionTrace"`
	Type             PlainTransactionTraceWithTypeDtoType                     `json:"type"`
}

// PlainTransactionTraceWithTypeDto_TransactionTrace_Item defines model for PlainTransactionTraceWithTypeDto.transactionTrace.Item.
type PlainTransactionTraceWithTypeDto_TransactionTrace_Item struct {
	union json.RawMessage
}

// PlainTransactionTraceWithTypeDtoType defines model for PlainTransactionTraceWithTypeDto.Type.
type PlainTransactionTraceWithTypeDtoType string

// ReadSyncedIntervalResponseDto defines model for ReadSyncedIntervalResponseDto.
type ReadSyncedIntervalResponseDto struct {
	// From Example: 1
	From float32 `json:"from"`

	// To Example: 14913951
	To float32 `json:"to"`
}

// BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody defines parameters for BlockTraceRestApiControllerBlockTraceByNumber.
type BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody struct {
	union json.RawMessage
}

// AsCoreCustomErrorTransactionTraceDto returns the union data inside the CoreCustomBlockTraceDto_Traces_Item as a CoreCustomErrorTransactionTraceDto
func (t CoreCustomBlockTraceDto_Traces_Item) AsCoreCustomErrorTransactionTraceDto() (CoreCustomErrorTransactionTraceDto, error) {
	var body CoreCustomErrorTransactionTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomErrorTransactionTraceDto overwrites any union data inside the CoreCustomBlockTraceDto_Traces_Item as the provided CoreCustomErrorTransactionTraceDto
func (t *CoreCustomBlockTraceDto_Traces_Item) FromCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomErrorTransactionTraceDto performs a merge with any union data inside the CoreCustomBlockTraceDto_Traces_Item, using the provided CoreCustomErrorTransactionTraceDto
func (t *CoreCustomBlockTraceDto_Traces_Item) MergeCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomRootTxEventCallstackTraceFullDto returns the union data inside the CoreCustomBlockTraceDto_Traces_Item as a CoreCustomRootTxEventCallstackTraceFullDto
func (t CoreCustomBlockTraceDto_Traces_Item) AsCoreCustomRootTxEventCallstackTraceFullDto() (CoreCustomRootTxEventCallstackTraceFullDto, error) {
	var body CoreCustomRootTxEventCallstackTraceFullDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomRootTxEventCallstackTraceFullDto overwrites any union data inside the CoreCustomBlockTraceDto_Traces_Item as the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *CoreCustomBlockTraceDto_Traces_Item) FromCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomRootTxEventCallstackTraceFullDto performs a merge with any union data inside the CoreCustomBlockTraceDto_Traces_Item, using the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *CoreCustomBlockTraceDto_Traces_Item) MergeCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CoreCustomBlockTraceDto_Traces_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CoreCustomBlockTraceDto_Traces_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCoreBuiltinTransactionRootSuccessTraceDto returns the union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as a CoreBuiltinTransactionRootSuccessTraceDto
func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) AsCoreBuiltinTransactionRootSuccessTraceDto() (CoreBuiltinTransactionRootSuccessTraceDto, error) {
	var body CoreBuiltinTransactionRootSuccessTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreBuiltinTransactionRootSuccessTraceDto overwrites any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as the provided CoreBuiltinTransactionRootSuccessTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) FromCoreBuiltinTransactionRootSuccessTraceDto(v CoreBuiltinTransactionRootSuccessTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreBuiltinTransactionRootSuccessTraceDto performs a merge with any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item, using the provided CoreBuiltinTransactionRootSuccessTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MergeCoreBuiltinTransactionRootSuccessTraceDto(v CoreBuiltinTransactionRootSuccessTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomErrorTransactionTraceDto returns the union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as a CoreCustomErrorTransactionTraceDto
func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) AsCoreCustomErrorTransactionTraceDto() (CoreCustomErrorTransactionTraceDto, error) {
	var body CoreCustomErrorTransactionTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomErrorTransactionTraceDto overwrites any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as the provided CoreCustomErrorTransactionTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) FromCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomErrorTransactionTraceDto performs a merge with any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item, using the provided CoreCustomErrorTransactionTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MergeCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomRootTxEventCallstackTraceFullDto returns the union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as a CoreCustomRootTxEventCallstackTraceFullDto
func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) AsCoreCustomRootTxEventCallstackTraceFullDto() (CoreCustomRootTxEventCallstackTraceFullDto, error) {
	var body CoreCustomRootTxEventCallstackTraceFullDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomRootTxEventCallstackTraceFullDto overwrites any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) FromCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomRootTxEventCallstackTraceFullDto performs a merge with any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item, using the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MergeCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCoreBuiltinBlockTracesDto returns the union data inside the BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody as a CoreBuiltinBlockTracesDto
func (t BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) AsCoreBuiltinBlockTracesDto() (CoreBuiltinBlockTracesDto, error) {
	var body CoreBuiltinBlockTracesDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreBuiltinBlockTracesDto overwrites any union data inside the BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody as the provided CoreBuiltinBlockTracesDto
func (t *BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) FromCoreBuiltinBlockTracesDto(v CoreBuiltinBlockTracesDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreBuiltinBlockTracesDto performs a merge with any union data inside the BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody, using the provided CoreBuiltinBlockTracesDto
func (t *BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) MergeCoreBuiltinBlockTracesDto(v CoreBuiltinBlockTracesDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomBlockTraceDto returns the union data inside the BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody as a CoreCustomBlockTraceDto
func (t BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) AsCoreCustomBlockTraceDto() (CoreCustomBlockTraceDto, error) {
	var body CoreCustomBlockTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomBlockTraceDto overwrites any union data inside the BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody as the provided CoreCustomBlockTraceDto
func (t *BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) FromCoreCustomBlockTraceDto(v CoreCustomBlockTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomBlockTraceDto performs a merge with any union data inside the BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody, using the provided CoreCustomBlockTraceDto
func (t *BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) MergeCoreCustomBlockTraceDto(v CoreCustomBlockTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BlockTraceRestApiControllerBlockTraceByNumber200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
