// Package traces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package traces

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CoreBuiltinBlockTracesDtoType.
const (
	CoreBuiltinBlockTracesDtoTypeBUILTIN             CoreBuiltinBlockTracesDtoType = "BUILTIN"
	CoreBuiltinBlockTracesDtoTypeCUSTOM              CoreBuiltinBlockTracesDtoType = "CUSTOM"
	CoreBuiltinBlockTracesDtoTypeCUSTOMGO            CoreBuiltinBlockTracesDtoType = "CUSTOM_GO"
	CoreBuiltinBlockTracesDtoTypeCUSTOMWITHOUTSTORE  CoreBuiltinBlockTracesDtoType = "CUSTOM_WITHOUT_STORE"
	CoreBuiltinBlockTracesDtoTypeOLDARBITRUMRAWTRACE CoreBuiltinBlockTracesDtoType = "OLD_ARBITRUM_RAW_TRACE"
)

// Defines values for CoreBuiltinCallTraceDtoType.
const (
	CoreBuiltinCallTraceDtoTypeCALL          CoreBuiltinCallTraceDtoType = "CALL"
	CoreBuiltinCallTraceDtoTypeCALLCODE      CoreBuiltinCallTraceDtoType = "CALLCODE"
	CoreBuiltinCallTraceDtoTypeCREATE        CoreBuiltinCallTraceDtoType = "CREATE"
	CoreBuiltinCallTraceDtoTypeCREATE2       CoreBuiltinCallTraceDtoType = "CREATE2"
	CoreBuiltinCallTraceDtoTypeDELEGATECALL  CoreBuiltinCallTraceDtoType = "DELEGATECALL"
	CoreBuiltinCallTraceDtoTypeINVALID       CoreBuiltinCallTraceDtoType = "INVALID"
	CoreBuiltinCallTraceDtoTypeSELFDESTRUCT  CoreBuiltinCallTraceDtoType = "SELFDESTRUCT"
	CoreBuiltinCallTraceDtoTypeSTATICCALL    CoreBuiltinCallTraceDtoType = "STATICCALL"
	CoreBuiltinCallTraceDtoTypeSTOP          CoreBuiltinCallTraceDtoType = "STOP"
	CoreBuiltinCallTraceDtoTypeTRANSFERETHER CoreBuiltinCallTraceDtoType = "TRANSFER_ETHER"
)

// Defines values for CoreBuiltinTransactionRootSuccessTraceDtoType.
const (
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCALL          CoreBuiltinTransactionRootSuccessTraceDtoType = "CALL"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCALLCODE      CoreBuiltinTransactionRootSuccessTraceDtoType = "CALLCODE"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCREATE        CoreBuiltinTransactionRootSuccessTraceDtoType = "CREATE"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeCREATE2       CoreBuiltinTransactionRootSuccessTraceDtoType = "CREATE2"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeDELEGATECALL  CoreBuiltinTransactionRootSuccessTraceDtoType = "DELEGATECALL"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeINVALID       CoreBuiltinTransactionRootSuccessTraceDtoType = "INVALID"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeSELFDESTRUCT  CoreBuiltinTransactionRootSuccessTraceDtoType = "SELFDESTRUCT"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeSTATICCALL    CoreBuiltinTransactionRootSuccessTraceDtoType = "STATICCALL"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeSTOP          CoreBuiltinTransactionRootSuccessTraceDtoType = "STOP"
	CoreBuiltinTransactionRootSuccessTraceDtoTypeTRANSFERETHER CoreBuiltinTransactionRootSuccessTraceDtoType = "TRANSFER_ETHER"
)

// Defines values for CoreCustomBlockTraceDtoType.
const (
	CoreCustomBlockTraceDtoTypeBUILTIN             CoreCustomBlockTraceDtoType = "BUILTIN"
	CoreCustomBlockTraceDtoTypeCUSTOM              CoreCustomBlockTraceDtoType = "CUSTOM"
	CoreCustomBlockTraceDtoTypeCUSTOMGO            CoreCustomBlockTraceDtoType = "CUSTOM_GO"
	CoreCustomBlockTraceDtoTypeCUSTOMWITHOUTSTORE  CoreCustomBlockTraceDtoType = "CUSTOM_WITHOUT_STORE"
	CoreCustomBlockTraceDtoTypeOLDARBITRUMRAWTRACE CoreCustomBlockTraceDtoType = "OLD_ARBITRUM_RAW_TRACE"
)

// Defines values for CoreCustomRootTxEventCallstackTraceFullDtoStatus.
const (
	CoreCustomRootTxEventCallstackTraceFullDtoStatusERROR          CoreCustomRootTxEventCallstackTraceFullDtoStatus = "ERROR"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusERRORUNWIND    CoreCustomRootTxEventCallstackTraceFullDtoStatus = "ERROR_UNWIND"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusINVALIDOPCODE  CoreCustomRootTxEventCallstackTraceFullDtoStatus = "INVALID_OPCODE"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusNOCONTRACT     CoreCustomRootTxEventCallstackTraceFullDtoStatus = "NO_CONTRACT"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusOUTOFGAS       CoreCustomRootTxEventCallstackTraceFullDtoStatus = "OUT_OF_GAS"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusRETURNED       CoreCustomRootTxEventCallstackTraceFullDtoStatus = "RETURNED"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusREVERTED       CoreCustomRootTxEventCallstackTraceFullDtoStatus = "REVERTED"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusSELFDESTRUCTED CoreCustomRootTxEventCallstackTraceFullDtoStatus = "SELFDESTRUCTED"
	CoreCustomRootTxEventCallstackTraceFullDtoStatusSTOPPED        CoreCustomRootTxEventCallstackTraceFullDtoStatus = "STOPPED"
)

// Defines values for CoreCustomRootTxEventCallstackTraceFullDtoType.
const (
	CALL          CoreCustomRootTxEventCallstackTraceFullDtoType = "CALL"
	CALLCODE      CoreCustomRootTxEventCallstackTraceFullDtoType = "CALLCODE"
	CREATE        CoreCustomRootTxEventCallstackTraceFullDtoType = "CREATE"
	CREATE2       CoreCustomRootTxEventCallstackTraceFullDtoType = "CREATE2"
	DELEGATECALL  CoreCustomRootTxEventCallstackTraceFullDtoType = "DELEGATECALL"
	INVALID       CoreCustomRootTxEventCallstackTraceFullDtoType = "INVALID"
	SELFDESTRUCT  CoreCustomRootTxEventCallstackTraceFullDtoType = "SELFDESTRUCT"
	STATICCALL    CoreCustomRootTxEventCallstackTraceFullDtoType = "STATICCALL"
	STOP          CoreCustomRootTxEventCallstackTraceFullDtoType = "STOP"
	TRANSFERETHER CoreCustomRootTxEventCallstackTraceFullDtoType = "TRANSFER_ETHER"
)

// Defines values for CoreCustomTxEventCallstackTraceDtoStatus.
const (
	CoreCustomTxEventCallstackTraceDtoStatusERROR          CoreCustomTxEventCallstackTraceDtoStatus = "ERROR"
	CoreCustomTxEventCallstackTraceDtoStatusERRORUNWIND    CoreCustomTxEventCallstackTraceDtoStatus = "ERROR_UNWIND"
	CoreCustomTxEventCallstackTraceDtoStatusINVALIDOPCODE  CoreCustomTxEventCallstackTraceDtoStatus = "INVALID_OPCODE"
	CoreCustomTxEventCallstackTraceDtoStatusNOCONTRACT     CoreCustomTxEventCallstackTraceDtoStatus = "NO_CONTRACT"
	CoreCustomTxEventCallstackTraceDtoStatusOUTOFGAS       CoreCustomTxEventCallstackTraceDtoStatus = "OUT_OF_GAS"
	CoreCustomTxEventCallstackTraceDtoStatusRETURNED       CoreCustomTxEventCallstackTraceDtoStatus = "RETURNED"
	CoreCustomTxEventCallstackTraceDtoStatusREVERTED       CoreCustomTxEventCallstackTraceDtoStatus = "REVERTED"
	CoreCustomTxEventCallstackTraceDtoStatusSELFDESTRUCTED CoreCustomTxEventCallstackTraceDtoStatus = "SELFDESTRUCTED"
	CoreCustomTxEventCallstackTraceDtoStatusSTOPPED        CoreCustomTxEventCallstackTraceDtoStatus = "STOPPED"
)

// Defines values for PlainTransactionTraceWithTypeDtoType.
const (
	BUILTIN             PlainTransactionTraceWithTypeDtoType = "BUILTIN"
	CUSTOM              PlainTransactionTraceWithTypeDtoType = "CUSTOM"
	CUSTOMGO            PlainTransactionTraceWithTypeDtoType = "CUSTOM_GO"
	CUSTOMWITHOUTSTORE  PlainTransactionTraceWithTypeDtoType = "CUSTOM_WITHOUT_STORE"
	OLDARBITRUMRAWTRACE PlainTransactionTraceWithTypeDtoType = "OLD_ARBITRUM_RAW_TRACE"
)

// CoreBuiltinBlockTracesDto defines model for CoreBuiltinBlockTracesDto.
type CoreBuiltinBlockTracesDto struct {
	BlockHash      string                                      `json:"blockHash"`
	BlockNumber    *float32                                    `json:"blockNumber,omitempty"`
	BlockTimestamp string                                      `json:"blockTimestamp"`
	Traces         []CoreBuiltinTransactionRootSuccessTraceDto `json:"traces"`
	Type           CoreBuiltinBlockTracesDtoType               `json:"type"`
	Version        string                                      `json:"version"`
}

// CoreBuiltinBlockTracesDtoType defines model for CoreBuiltinBlockTracesDto.Type.
type CoreBuiltinBlockTracesDtoType string

// CoreBuiltinCallTraceDto defines model for CoreBuiltinCallTraceDto.
type CoreBuiltinCallTraceDto struct {
	Calls            []CoreBuiltinCallTraceDto   `json:"calls"`
	Error            string                      `json:"error"`
	From             string                      `json:"from"`
	Gas              string                      `json:"gas"`
	GasUsed          float32                     `json:"gasUsed"`
	Input            string                      `json:"input"`
	IsParentHasError bool                        `json:"isParentHasError"`
	Output           string                      `json:"output"`
	To               string                      `json:"to"`
	Type             CoreBuiltinCallTraceDtoType `json:"type"`
	Value            string                      `json:"value"`
}

// CoreBuiltinCallTraceDtoType defines model for CoreBuiltinCallTraceDto.Type.
type CoreBuiltinCallTraceDtoType string

// CoreBuiltinTraceLogDto defines model for CoreBuiltinTraceLogDto.
type CoreBuiltinTraceLogDto struct {
	Contract string          `json:"contract"`
	Data     string          `json:"data"`
	Topics   [][]interface{} `json:"topics"`
}

// CoreBuiltinTransactionRootSuccessTraceDto defines model for CoreBuiltinTransactionRootSuccessTraceDto.
type CoreBuiltinTransactionRootSuccessTraceDto struct {
	Calls                []CoreBuiltinCallTraceDto                     `json:"calls"`
	Error                string                                        `json:"error"`
	Events               []CoreBuiltinTraceLogDto                      `json:"events"`
	From                 string                                        `json:"from"`
	Gas                  string                                        `json:"gas"`
	GasHex               string                                        `json:"gasHex"`
	GasPrice             string                                        `json:"gasPrice"`
	GasUsed              float32                                       `json:"gasUsed"`
	Input                string                                        `json:"input"`
	MaxFeePerGas         string                                        `json:"maxFeePerGas"`
	MaxPriorityFeePerGas string                                        `json:"maxPriorityFeePerGas"`
	Nonce                string                                        `json:"nonce"`
	Output               string                                        `json:"output"`
	RevertReason         string                                        `json:"revertReason"`
	To                   string                                        `json:"to"`
	TxHash               string                                        `json:"txHash"`
	Type                 CoreBuiltinTransactionRootSuccessTraceDtoType `json:"type"`
	Value                string                                        `json:"value"`
}

// CoreBuiltinTransactionRootSuccessTraceDtoType defines model for CoreBuiltinTransactionRootSuccessTraceDto.Type.
type CoreBuiltinTransactionRootSuccessTraceDtoType string

// CoreCustomBlockTraceDto defines model for CoreCustomBlockTraceDto.
type CoreCustomBlockTraceDto struct {
	BlockHash      string                                `json:"blockHash"`
	BlockTimestamp string                                `json:"blockTimestamp"`
	Number         float32                               `json:"number"`
	Traces         []CoreCustomBlockTraceDto_Traces_Item `json:"traces"`
	Type           CoreCustomBlockTraceDtoType           `json:"type"`
	Version        string                                `json:"version"`
}

// CoreCustomBlockTraceDto_Traces_Item defines model for CoreCustomBlockTraceDto.traces.Item.
type CoreCustomBlockTraceDto_Traces_Item struct {
	union json.RawMessage
}

// CoreCustomBlockTraceDtoType defines model for CoreCustomBlockTraceDto.Type.
type CoreCustomBlockTraceDtoType string

// CoreCustomErrorTransactionTraceDto defines model for CoreCustomErrorTransactionTraceDto.
type CoreCustomErrorTransactionTraceDto struct {
	Error                string `json:"error"`
	GasHex               string `json:"gasHex"`
	GasPrice             string `json:"gasPrice"`
	MaxFeePerGas         string `json:"maxFeePerGas"`
	MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`
	Nonce                string `json:"nonce"`
	TxHash               string `json:"txHash"`
}

// CoreCustomRootTxEventCallstackTraceFullDto defines model for CoreCustomRootTxEventCallstackTraceFullDto.
type CoreCustomRootTxEventCallstackTraceFullDto struct {
	Address              string                                           `json:"address"`
	Calls                []CoreCustomTxEventCallstackTraceDto             `json:"calls"`
	Depth                float32                                          `json:"depth"`
	DestructAddress      string                                           `json:"destructAddress"`
	ErrorDetails         string                                           `json:"errorDetails"`
	From                 string                                           `json:"from"`
	GasActual            float32                                          `json:"gasActual"`
	GasHex               string                                           `json:"gasHex"`
	GasLimit             float32                                          `json:"gasLimit"`
	GasPrice             string                                           `json:"gasPrice"`
	GasRefund            float32                                          `json:"gasRefund"`
	GasUsed              float32                                          `json:"gasUsed"`
	Input                string                                           `json:"input"`
	IntrinsicGas         float32                                          `json:"intrinsicGas"`
	Logs                 []CoreCustomTraceLogDto                          `json:"logs"`
	MaxFeePerGas         string                                           `json:"maxFeePerGas"`
	MaxPriorityFeePerGas string                                           `json:"maxPriorityFeePerGas"`
	Nonce                string                                           `json:"nonce"`
	Output               string                                           `json:"output"`
	Res                  string                                           `json:"res"`
	Status               CoreCustomRootTxEventCallstackTraceFullDtoStatus `json:"status"`
	Storage              []CustomStorageDto                               `json:"storage"`
	Success              float32                                          `json:"success"`
	Time                 string                                           `json:"time"`
	To                   string                                           `json:"to"`
	TxHash               string                                           `json:"txHash"`
	Type                 CoreCustomRootTxEventCallstackTraceFullDtoType   `json:"type"`
	Value                string                                           `json:"value"`
}

// CoreCustomRootTxEventCallstackTraceFullDtoStatus defines model for CoreCustomRootTxEventCallstackTraceFullDto.Status.
type CoreCustomRootTxEventCallstackTraceFullDtoStatus string

// CoreCustomRootTxEventCallstackTraceFullDtoType defines model for CoreCustomRootTxEventCallstackTraceFullDto.Type.
type CoreCustomRootTxEventCallstackTraceFullDtoType string

// CoreCustomTraceLogDto defines model for CoreCustomTraceLogDto.
type CoreCustomTraceLogDto struct {
	Contract string          `json:"contract"`
	Data     string          `json:"data"`
	Topics   [][]interface{} `json:"topics"`
}

// CoreCustomTxEventCallstackTraceDto defines model for CoreCustomTxEventCallstackTraceDto.
type CoreCustomTxEventCallstackTraceDto struct {
	Address         string                                   `json:"address"`
	Calls           []CoreCustomTxEventCallstackTraceDto     `json:"calls"`
	Depth           float32                                  `json:"depth"`
	DestructAddress string                                   `json:"destructAddress"`
	ErrorDetails    string                                   `json:"errorDetails"`
	From            string                                   `json:"from"`
	Gas             string                                   `json:"gas"`
	GasCost         float32                                  `json:"gasCost"`
	GasLimit        float32                                  `json:"gasLimit"`
	GasUsed         float32                                  `json:"gasUsed"`
	Input           string                                   `json:"input"`
	Logs            []CoreCustomTraceLogDto                  `json:"logs"`
	Output          string                                   `json:"output"`
	PrevGasLimit    float32                                  `json:"prevGasLimit"`
	Res             string                                   `json:"res"`
	Status          CoreCustomTxEventCallstackTraceDtoStatus `json:"status"`
	Storage         []CustomStorageDto                       `json:"storage"`
	Success         float32                                  `json:"success"`
	Time            string                                   `json:"time"`
	To              string                                   `json:"to"`
	Type            string                                   `json:"type"`
	Value           string                                   `json:"value"`
}

// CoreCustomTxEventCallstackTraceDtoStatus defines model for CoreCustomTxEventCallstackTraceDto.Status.
type CoreCustomTxEventCallstackTraceDtoStatus string

// CustomStorageDto defines model for CustomStorageDto.
type CustomStorageDto struct {
	Key   string `json:"key"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

// PlainTransactionTraceWithTypeDto defines model for PlainTransactionTraceWithTypeDto.
type PlainTransactionTraceWithTypeDto struct {
	TransactionTrace []PlainTransactionTraceWithTypeDto_TransactionTrace_Item `json:"transactionTrace"`
	Type             PlainTransactionTraceWithTypeDtoType                     `json:"type"`
}

// PlainTransactionTraceWithTypeDto_TransactionTrace_Item defines model for PlainTransactionTraceWithTypeDto.transactionTrace.Item.
type PlainTransactionTraceWithTypeDto_TransactionTrace_Item struct {
	union json.RawMessage
}

// PlainTransactionTraceWithTypeDtoType defines model for PlainTransactionTraceWithTypeDto.Type.
type PlainTransactionTraceWithTypeDtoType string

// ReadSyncedIntervalResponseDto defines model for ReadSyncedIntervalResponseDto.
type ReadSyncedIntervalResponseDto struct {
	From float32 `json:"from"`
	To   float32 `json:"to"`
}

// AsCoreCustomErrorTransactionTraceDto returns the union data inside the CoreCustomBlockTraceDto_Traces_Item as a CoreCustomErrorTransactionTraceDto
func (t CoreCustomBlockTraceDto_Traces_Item) AsCoreCustomErrorTransactionTraceDto() (CoreCustomErrorTransactionTraceDto, error) {
	var body CoreCustomErrorTransactionTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomErrorTransactionTraceDto overwrites any union data inside the CoreCustomBlockTraceDto_Traces_Item as the provided CoreCustomErrorTransactionTraceDto
func (t *CoreCustomBlockTraceDto_Traces_Item) FromCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomErrorTransactionTraceDto performs a merge with any union data inside the CoreCustomBlockTraceDto_Traces_Item, using the provided CoreCustomErrorTransactionTraceDto
func (t *CoreCustomBlockTraceDto_Traces_Item) MergeCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomRootTxEventCallstackTraceFullDto returns the union data inside the CoreCustomBlockTraceDto_Traces_Item as a CoreCustomRootTxEventCallstackTraceFullDto
func (t CoreCustomBlockTraceDto_Traces_Item) AsCoreCustomRootTxEventCallstackTraceFullDto() (CoreCustomRootTxEventCallstackTraceFullDto, error) {
	var body CoreCustomRootTxEventCallstackTraceFullDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomRootTxEventCallstackTraceFullDto overwrites any union data inside the CoreCustomBlockTraceDto_Traces_Item as the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *CoreCustomBlockTraceDto_Traces_Item) FromCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomRootTxEventCallstackTraceFullDto performs a merge with any union data inside the CoreCustomBlockTraceDto_Traces_Item, using the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *CoreCustomBlockTraceDto_Traces_Item) MergeCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t CoreCustomBlockTraceDto_Traces_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CoreCustomBlockTraceDto_Traces_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCoreBuiltinTransactionRootSuccessTraceDto returns the union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as a CoreBuiltinTransactionRootSuccessTraceDto
func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) AsCoreBuiltinTransactionRootSuccessTraceDto() (CoreBuiltinTransactionRootSuccessTraceDto, error) {
	var body CoreBuiltinTransactionRootSuccessTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreBuiltinTransactionRootSuccessTraceDto overwrites any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as the provided CoreBuiltinTransactionRootSuccessTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) FromCoreBuiltinTransactionRootSuccessTraceDto(v CoreBuiltinTransactionRootSuccessTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreBuiltinTransactionRootSuccessTraceDto performs a merge with any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item, using the provided CoreBuiltinTransactionRootSuccessTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MergeCoreBuiltinTransactionRootSuccessTraceDto(v CoreBuiltinTransactionRootSuccessTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomErrorTransactionTraceDto returns the union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as a CoreCustomErrorTransactionTraceDto
func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) AsCoreCustomErrorTransactionTraceDto() (CoreCustomErrorTransactionTraceDto, error) {
	var body CoreCustomErrorTransactionTraceDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomErrorTransactionTraceDto overwrites any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as the provided CoreCustomErrorTransactionTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) FromCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomErrorTransactionTraceDto performs a merge with any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item, using the provided CoreCustomErrorTransactionTraceDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MergeCoreCustomErrorTransactionTraceDto(v CoreCustomErrorTransactionTraceDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsCoreCustomRootTxEventCallstackTraceFullDto returns the union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as a CoreCustomRootTxEventCallstackTraceFullDto
func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) AsCoreCustomRootTxEventCallstackTraceFullDto() (CoreCustomRootTxEventCallstackTraceFullDto, error) {
	var body CoreCustomRootTxEventCallstackTraceFullDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCoreCustomRootTxEventCallstackTraceFullDto overwrites any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item as the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) FromCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCoreCustomRootTxEventCallstackTraceFullDto performs a merge with any union data inside the PlainTransactionTraceWithTypeDto_TransactionTrace_Item, using the provided CoreCustomRootTxEventCallstackTraceFullDto
func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MergeCoreCustomRootTxEventCallstackTraceFullDto(v CoreCustomRootTxEventCallstackTraceFullDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t PlainTransactionTraceWithTypeDto_TransactionTrace_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PlainTransactionTraceWithTypeDto_TransactionTrace_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
