// Package web3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package web3

// Defines values for PostChainIdNodeTypeParamsNodeType.
const (
	Archive PostChainIdNodeTypeParamsNodeType = "archive"
	Full    PostChainIdNodeTypeParamsNodeType = "full"
)

// Valid indicates whether the value is a known member of the PostChainIdNodeTypeParamsNodeType enum.
func (e PostChainIdNodeTypeParamsNodeType) Valid() bool {
	switch e {
	case Archive:
		return true
	case Full:
		return true
	default:
		return false
	}
}

// PostChainIdJSONBody defines parameters for PostChainId.
type PostChainIdJSONBody struct {
	// Id An identifier established by the client
	//
	// Example: 1
	Id string `json:"id,omitempty"`

	// Jsonrpc JSON-RPC version, typically "2.0"
	//
	// Example: 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Method The name of the RPC method to be invoked
	//
	// Example: eth_blockNumber
	Method string `json:"method"`

	// Params Parameters for the RPC method
	//
	// Example: []
	Params []string `json:"params,omitempty"`
}

// PostChainIdNodeTypeJSONBody defines parameters for PostChainIdNodeType.
type PostChainIdNodeTypeJSONBody struct {
	// Id An identifier established by the client
	//
	// Example: 1
	Id int `json:"id,omitempty"`

	// Jsonrpc JSON-RPC version, typically "2.0"
	//
	// Example: 2.0
	Jsonrpc string `json:"jsonrpc,omitempty"`

	// Method The name of the RPC method to be invoked
	//
	// Example: eth_blockNumber
	Method string `json:"method,omitempty"`

	// Params Parameters for the RPC method
	//
	// Example: []
	Params []string `json:"params,omitempty"`
}

// PostChainIdNodeTypeParamsNodeType defines parameters for PostChainIdNodeType.
type PostChainIdNodeTypeParamsNodeType string

// PostChainIdJSONRequestBody defines body for PostChainId for application/json ContentType.
type PostChainIdJSONRequestBody PostChainIdJSONBody

// PostChainIdNodeTypeJSONRequestBody defines body for PostChainIdNodeType for application/json ContentType.
type PostChainIdNodeTypeJSONRequestBody PostChainIdNodeTypeJSONBody
